inf_dict = {
    "abastecer": ["to supply", "to provide", "to stock (up)"],
    "absolver": ["to absolve", "to acquit", "to pardon"],
    "abstenerse": ["to abstain", "to refrain (from)", "to hold back (oneself)"],
    "abstraer": ["to abstract", "to detach", "to withdraw (one’s mind)"],
    "acertar": ["to guess correctly", "to get right", "to hit the mark"],
    "acoger": ["to welcome", "to receive", "to embrace"],
    "acontecer": ["to happen", "to occur", "to take place"],
    "acordar": ["to accede", "to consent", "to agree"],
    "acostar": ["to put (someone) to bed", "to lay down (someone)", "to bed down (someone)"],
    "acostarse": ["to go to bed", "to lie down", "to turn in"],
    "adherir": ["to adhere", "to stick", "to attach"],
    "adormecer": ["to lull to sleep", "to numb", "to make drowsy"],
    "adquirir": ["to acquire", "to buy", "to get"],
    "aducir": ["to adduce", "to put forward (e.g., evidence)", "to present (arguments)"],
    "advertir": ["to warn", "to caution", "to alert"],
    "agradecer": ["to thank", "to appreciate", "to acknowledge"],
    "almorzar": ["to have lunch", "to eat lunch", "to dine (at midday)"],
    "aparecer": ["to appear", "to show up", "to come out"],
    "apetecer": ["to feel like (doing/having)", "to fancy", "to crave"],
    "apostar": ["to bet", "to wager", "to gamble"],
    "apretar": ["to tighten", "to press", "to squeeze"],
    "aprobar": ["to pass (an exam)", "to approve", "to endorse"],
    "arrepentirse": ["to repent", "to regret", "to be sorry"],
    "ascender": ["to ascend", "to rise", "to be promoted"],
    "asentir": ["to agree", "to assent", "to consent"],
    "asir": ["to grasp", "to seize", "to clutch"],
    "atenerse": ["to abide by", "to stick to", "to follow (rules or guidelines)"],
    "atraer": ["to attract", "to draw", "to appeal (to someone)"],
    "avenirse": ["to come to an agreement", "to come to terms", "to reconcile (oneself)"],
    "avergonzar": ["to embarrass", "to shame", "to mortify"],
    "avergonzarse": ["to feel embarrassed", "to be ashamed", "to become ashamed"],
    "bendecir": ["to bless", "to sanctify", "to consecrate"],
    "caber": ["to fit", "to accommodate", "to hold"],
    "caer": ["to fall", "to drop", "to tumble"],
    "calentar": ["to heat", "to warm", "to heat up"],
    "carecer": ["to lack", "to be without", "to be deficient in"],
    "cegar": ["to blind", "to dazzle", "to impair vision"],
    "ceñir": ["to encircle", "to gird", "to wrap around"],
    "cerrar": ["to close", "to shut", "to conclude"],
    "cocer": ["to cook", "to boil", "to simmer"],
    "colar": ["to strain", "to filter", "to sieve"],
    "colarse": ["to sneak in", "to slip in", "to get in uninvited"],
    "colegir": ["to deduce", "to infer", "to conclude"],
    "colgar": ["to hang", "to suspend", "to dangle"],
    "comenzar": ["to begin", "to start", "to initiate"],
    "compadecer": ["to pity", "to feel compassion for", "to sympathize with"],
    "comparecer": ["to appear", "to attend (a summons)", "to show up"],
    "complacer": ["to please", "to satisfy", "to gratify"],
    "componer": ["to compose", "to put together", "to construct"],
    "comprobar": ["to verify", "to check", "to ascertain"],
    "concebir": ["to conceive", "to form", "to develop (an idea)"],
    "concertar": ["to arrange", "to schedule", "to organize"],
    "concluir": ["to conclude", "to finish", "to complete"],
    "concordar": ["to agree", "to harmonize", "to be in accord"],
    "conducir": ["to drive", "to operate", "to steer"],
    "conferir": ["to confer", "to bestow", "to award"],
    "confesar": ["to confess", "to admit", "to acknowledge"],
    "conmover": ["to move (emotionally)", "to affect", "to stir"],
    "conocer": ["to know", "to be familiar with", "to recognize"],
    "conseguir": ["to get", "to obtain", "to acquire"],
    "consentir": ["to consent", "to allow", "to indulge"],
    "consolar": ["to console", "to comfort", "to soothe"],
    "construir": ["to build", "to construct", "to erect"],
    "contar": ["to count", "to tell", "to narrate"],
    "contender": ["to contend", "to compete", "to struggle"],
    "contener": ["to contain", "to hold", "to restrain"],
    "contradecir": ["to contradict", "to dispute", "to oppose"],
    "contraer": ["to contract", "to shrink", "to draw together"],
    "contravenir": ["to contravene", "to violate", "to disobey"],
    "convenir": ["to agree", "to suit", "to befit"],
    "convertir": ["to convert", "to transform", "to change"],
    "convertirse": ["to become", "to turn into", "to transform"],
    "corregir": ["to correct", "to rectify", "to amend"],
    "costar": ["to cost", "to price", "to value"],
    "crecer": ["to grow", "to increase", "to develop"],
    "dar": ["to give", "to grant", "to offer"],
    "darse": ["to give oneself", "to yield", "to offer oneself"],
    "decaer": ["to decline", "to deteriorate", "to languish"],
    "decir": ["to say", "to tell", "to express"],
    "decrecer": ["to decrease", "to diminish", "to wane"],
    "deducir": ["to deduce", "to infer", "to derive"],
    "defender": ["to defend", "to protect", "to uphold"],
    "deferir": ["to differ", "to vary", "to dissent"],
    "degollar": ["to slit the throat", "to cut the throat", "to execute"],
    "demoler": ["to demolish", "to tear down", "to knock down"],
    "demostrar": ["to demonstrate", "to show", "to prove"],
    "denegar": ["to deny", "to refuse", "to reject"],
    "deponer": ["to depose", "to remove", "to overthrow"],
    "derretir": ["to melt", "to liquefy", "to dissolve"],
    "derretirse": ["to melt (oneself)", "to liquefy", "to dissolve"],
    "desaparecer": ["to disappear", "to vanish", "to fade away"],
    "desatender": ["to neglect", "to disregard", "to ignore"],
    "descender": ["to descend", "to go down", "to decline"],
    "descomponer": ["to decompose", "to break down", "to decay"],
    "descontar": ["to discount", "to deduct", "to subtract"],
    "desdecir": ["to take back one’s words", "to retract", "to recant"],
    "deshacer": ["to undo", "to unmake", "to dismantle"],
    "deshacerse": ["to undo oneself", "to disintegrate", "to break down"],
    "desobedecer": ["to disobey", "to defy", "to disregard"],
    "despedir": ["to dismiss", "to say goodbye", "to fire"],
    "despedirse": ["to say goodbye", "to take leave", "to bid farewell"],
    "despertar": ["to wake (someone) up", "to rouse", "to awaken"],
    "despertarse": ["to wake up", "to get up", "to arise"],
    "desteñir": ["to fade", "to discolor", "to lose color"],
    "desvanecerse": ["to vanish", "to fade away", "to faint"],
    "desvestir": ["to undress", "to strip", "to disrobe"],
    "desvestirse": ["to get undressed", "to strip off", "to disrobe oneself"],
    "destruir": ["to destroy", "to demolish", "to ruin"],
    "detener": ["to stop", "to halt", "to impede"],
    "detenerse": ["to come to a stop", "to pause", "to halt"],
    "devenir": ["to become", "to turn into", "to evolve into"],
    "devolver": ["to return", "to give back", "to restore"],
    "diferir": ["to differ", "to vary", "to disagree"],
    "digerir": ["to digest", "to assimilate", "to absorb"],
    "discernir": ["to discern", "to distinguish", "to perceive"],
    "disentir": ["to dissent", "to disagree", "to differ"],
    "disolver": ["to dissolve", "to disintegrate", "to melt"],
    "disponer": ["to arrange", "to set up", "to plan"],
    "disponerse": ["to get ready", "to prepare oneself", "to brace oneself"],
    "distender": ["to relax", "to ease", "to loosen"],
    "distraer": ["to distract", "to divert", "to sidetrack"],
    "distraerse": ["to get distracted", "to lose focus", "to become sidetracked"],
    "divertir": ["to entertain", "to amuse", "to delight"],
    "divertirse": ["to have fun", "to enjoy oneself", "to amuse oneself"],
    "doler": ["to hurt", "to ache", "to cause pain"],
    "dormir": ["to sleep", "to slumber", "to doze"],
    "dormirse": ["to fall asleep", "to nod off", "to drift off"],
    "elegir": ["to choose", "to select", "to pick"],
    "embellecer": ["to beautify", "to adorn", "to embellish"],
    "embestir": ["to charge", "to rush", "to assault"],
    "empezar": ["to begin", "to start", "to commence"],
    "empobrecer": ["to impoverish", "to make poor", "to enfeeble"],
    "enaltecer": ["to exalt", "to glorify", "to ennoble"],
    "encender": ["to light", "to ignite", "to turn on"],
    "encerrar": ["to enclose", "to confine", "to lock up"],
    "encomendar": ["to entrust", "to commend", "to hand over"],
    "encontrar": ["to find", "to discover", "to locate"],
    "encontrarse": ["to meet", "to be located", "to find oneself"],
    "enflaquecerse": ["to become thin", "to slim down", "to lose weight"],
    "enloquecer": ["to go crazy", "to drive mad", "to become insane"],
    "enmendar": ["to amend", "to correct", "to rectify"],
    "enriquecer": ["to enrich", "to make richer", "to enhance"],
    "enriquecerse": ["to get richer", "to become enriched", "to prosper"],
    "ensordecer": ["to deafen", "to make deaf", "to dull"],
    "entender": ["to understand", "to comprehend", "to grasp"],
    "enterrar": ["to bury", "to inter", "to lay to rest"],
    "entretener": ["to entertain", "to amuse", "to engage"],
    "entretenerse": ["to have fun", "to be amused", "to enjoy oneself"],
    "entrever": ["to glimpse", "to catch sight of", "to discern"],
    "entristecer": ["to sadden", "to depress", "to grieve"],
    "envejecer": ["to age", "to grow old", "to become old"],
    "envolver": ["to wrap", "to envelop", "to encircle"],
    "equivaler": ["to equal", "to be equivalent to", "to correspond"],
    "erguir": ["to erect", "to raise", "to set upright"],
    "esclarecer": ["to clarify", "to elucidate", "to explain"],
    "escoger": ["to pick out", "to choose", "to elect"],
    "establecer": ["to establish", "to set up", "to found"],
    "estar": ["to be", "to exist", "to remain"],
    "estremecer": ["to shudder", "to shake", "to tremble"],
    "exponer": ["to expose", "to exhibit", "to display"],
    "extender": ["to extend", "to stretch", "to spread"],
    "extraer": ["to extract", "to remove", "to draw out"],
    "fallecer": ["to die", "to pass away", "to expire"],
    "favorecer": ["to favor", "to support", "to benefit"],
    "fingir": ["to pretend", "to feign", "to simulate"],
    "florecer": ["to flourish", "to bloom", "to prosper"],
    "fortalecer": ["to strengthen", "to fortify", "to reinforce"],
    "freír": ["to fry", "to cook", "to crisp"],
    "fluir": ["to flow", "to stream", "to run"],
    "gemir": ["to moan", "to groan", "to lament"],
    "gobernar": ["to govern", "to command", "to control"],
    "guarnecer": ["to furnish", "to equip", "to supply"],
    "haber": ["to have (auxiliary)", "to exist", "to occur"],
    "hacer": ["to do", "to make", "to perform"],
    "hacerse": ["to become", "to get", "to turn oneself"],
    "henchir": ["to swell", "to puff up", "to fill"],
    "hender": ["to split", "to cleave", "to crack"],
    "herir": ["to injure", "to wound", "to hurt"],
    "herrar": ["to shoe (a horse)", "to fit with horseshoes", "to nail horseshoes"],
    "hervir": ["to boil", "to seethe", "to simmer"],
    "huir": ["to flee", "to escape", "to run away"],
    "humedecer": ["to moisten", "to dampen", "to wet"],
    "impedir": ["to prevent", "to hinder", "to stop"],
    "imponer": ["to impose", "to inflict", "to enforce"],
    "inducir": ["to induce", "to prompt", "to persuade"],
    "inferir": ["to infer", "to deduce", "to conclude"],
    "ingerir": ["to ingest", "to consume", "to swallow"],
    "inquirir": ["to inquire", "to investigate", "to question"],
    "interferir": ["to interfere", "to meddle", "to intrude"],
    "interponer": ["to interpose", "to interject", "to insert"],
    "intervenir": ["to intervene", "to step in", "to get involved"],
    "introducir": ["to introduce", "to insert", "to bring in"],
    "invertir": ["to invert", "to reverse", "to turn around"],
    "ir": ["to go", "to travel", "to proceed"],
    "irse": ["to leave", "to go away", "to depart"],
    "jugar": ["to play", "to compete", "to engage"],
    "lucir": ["to shine", "to display", "to exhibit"],
    "maldecir": ["to curse", "to damn", "to swear"],
    "malquerer": ["to dislike", "to detest", "to have ill will"],
    "mantener": ["to sustain", "to support", "to keep"],
    "mantenerse": ["to remain", "to stay", "to keep oneself"],
    "mecer": ["to rock", "to cradle", "to sway"],
    "medir": ["to measure", "to gauge", "to size"],
    "mentir": ["to lie", "to deceive", "to fib"],
    "merecer": ["to deserve", "to merit", "to earn"],
    "moler": ["to grind", "to mill", "to pulverize"],
    "morder": ["to bite", "to chomp", "to nibble"],
    "morir": ["to die", "to pass away", "to expire"],
    "morirse": ["to die", "to pass away", "to expire"],
    "mostrar": ["to show", "to display", "to exhibit"],
    "mostrarse": ["to show oneself", "to appear", "to reveal oneself"],
    "mover": ["to move", "to shift", "to stir"],
    "moverse": ["to move oneself", "to get moving", "to stir"],
    "nacer": ["to be born", "to originate", "to emerge"],
    "negar": ["to deny", "to reject", "to refute"],
    "negarse": ["to refuse", "to object", "to decline"],
    "obedecer": ["to obey", "to comply", "to follow"],
    "obtener": ["to obtain", "to get", "to acquire"],
    "ofrecer": ["to offer", "to present", "to provide"],
    "oír": ["to hear", "to listen", "to perceive"],
    "oler": ["to smell", "to sniff", "to scent"],
    "oponer": ["to oppose", "to counter", "to resist"],
    "oponerse": ["to oppose", "to object", "to resist"],
    "padecer": ["to suffer", "to endure", "to experience pain"],
    "parecer": ["to seem", "to appear", "to look"],
    "parecerse": ["to resemble", "to look like", "to mirror"],
    "pedir": ["to ask", "to request", "to order"],
    "pensar": ["to think", "to consider", "to reflect"],
    "perder": ["to lose", "to misplace", "to forfeit"],
    "perecer": ["to perish", "to die", "to pass away"],
    "permanecer": ["to remain", "to stay", "to continue"],
    "perseguir": ["to pursue", "to chase", "to follow"],
    "pertenecer": ["to belong", "to pertain", "to be part of"],
    "pervertir": ["to pervert", "to corrupt", "to debase"],
    "placer": ["to please", "to delight", "to satisfy"],
    "plegar": ["to fold", "to bend", "to crease"],
    "poder": ["to be able", "to can", "to manage"],
    "poner": ["to place", "to put", "to set"],
    "ponerse": ["to become", "to get", "to put on"],
    "posponer": ["to postpone", "to defer", "to put off"],
    "predecir": ["to predict", "to forecast", "to foretell"],
    "predisponer": ["to predispose", "to condition", "to incline"],
    "preferir": ["to prefer", "to favor", "to choose"],
    "presentir": ["to sense", "to forebode", "to have a premonition"],
    "presuponer": ["to presuppose", "to assume", "to take for granted"],
    "prevalecer": ["to prevail", "to dominate", "to be predominant"],
    "prevenir": ["to prevent", "to anticipate", "to avoid"],
    "prever": ["to foresee", "to anticipate", "to predict"],
    "probar": ["to test", "to try", "to taste"],
    "probarse": ["to try on", "to fit", "to test oneself"],
    "producir": ["to produce", "to create", "to generate"],
    "proferir": ["to utter", "to express", "to articulate"],
    "promover": ["to promote", "to advance", "to encourage"],
    "proponer": ["to propose", "to suggest", "to offer"],
    "proponerse": ["to resolve", "to intend", "to set oneself to"],
    "proseguir": ["to continue", "to proceed", "to go on"],
    "provenir": ["to come from", "to stem from", "to originate"],
    "quebrar": ["to break", "to shatter", "to fracture"],
    "quebrarse": ["to break (oneself)", "to fracture", "to collapse"],
    "querer": ["to want", "to desire", "to wish"],
    "raer": ["to scrape", "to erode", "to shave"],
    "reaparecer": ["to reappear", "to emerge again", "to show up again"],
    "recaer": ["to relapse", "to fall back", "to recur"],
    "recomendar": ["to recommend", "to advise", "to endorse"],
    "recomenzar": ["to restart", "to begin again", "to resume"],
    "reconocer": ["to recognize", "to acknowledge", "to identify"],
    "recordar": ["to remember", "to recall", "to remind"],
    "reducir": ["to reduce", "to decrease", "to diminish"],
    "referir": ["to refer", "to relate", "to recount"],
    "referirse": ["to refer to", "to allude to", "to mention"],
    "reforzar": ["to reinforce", "to strengthen", "to bolster"],
    "regar": ["to water", "to irrigate", "to sprinkle"],
    "regir": ["to govern", "to rule", "to direct"],
    "rehacer": ["to redo", "to remake", "to rebuild"],
    "reír": ["to laugh", "to chuckle", "to guffaw"],
    "reírse": ["to laugh", "to burst out laughing", "to chuckle"],
    "relucir": ["to shine", "to glisten", "to sparkle"],
    "remendar": ["to mend", "to patch", "to repair"],
    "remover": ["to remove", "to dislodge", "to stir"],
    "renacer": ["to be reborn", "to revive", "to arise"],
    "rendir": ["to yield", "to give in", "to perform"],
    "rendirse": ["to surrender", "to give up", "to capitulate"],
    "reñir": ["to scold", "to quarrel", "to chide"],
    "repetir": ["to repeat", "to reiterate", "to redo"],
    "reponer": ["to replace", "to restore", "to replenish"],
    "reproducir": ["to reproduce", "to replicate", "to copy"],
    "requerir": ["to require", "to need", "to demand"],
    "resolver": ["to solve", "to resolve", "to figure out"],
    "restablecer": ["to reestablish", "to restore", "to reinstate"],
    "retener": ["to retain", "to hold", "to keep"],
    "retorcer": ["to twist", "to wring", "to contort"],
    "reventar": ["to burst", "to explode", "to break open"],
    "revolver": ["to stir", "to mix", "to agitate"],
    "rodar": ["to roll", "to film", "to wander"],
    "roer": ["to gnaw", "to nibble", "to erode"],
    "rogar": ["to beg", "to implore", "to plead"],
    "saber": ["to know", "to understand", "to realize"],
    "salir": ["to leave", "to exit", "to depart"],
    "salirse": ["to leave", "to get out", "to stray"],
    "satisfacer": ["to satisfy", "to please", "to gratify"],
    "seducir": ["to seduce", "to allure", "to entice"],
    "seguir": ["to follow", "to pursue", "to continue"],
    "sembrar": ["to sow", "to plant", "to scatter"],
    "sentar": ["to suit", "to seat", "to settle"],
    "sentarse": ["to sit down", "to take a seat", "to settle oneself"],
    "sentir": ["to feel", "to sense", "to experience"],
    "sentirse": ["to feel", "to experience", "to be (emotionally)"],
    "ser": ["to be", "to exist", "to occur"],
    "serrar": ["to saw", "to cut with a saw", "to hack"],
    "servir": ["to serve", "to attend", "to cater"],
    "sobresalir": ["to stand out", "to excel", "to shine"],
    "sobrevolar": ["to fly over", "to soar above", "to hover over"],
    "sofreír": ["to sauté", "to fry lightly", "to stir-fry"],
    "soldar": ["to solder", "to weld", "to fuse"],
    "soler": ["to usually do", "to be wont to", "to tend to"],
    "soltar": ["to release", "to let go", "to free"],
    "sonar": ["to sound", "to ring", "to chime"],
    "sonarse": ["to blow one's nose", "to clear one's nose", "to unclog one's nostrils"],
    "sonreír": ["to smile", "to beam", "to grin"],
    "soñar": ["to dream", "to envision", "to imagine"],
    "sosegar": ["to calm", "to quiet", "to soothe"],
    "sostener": ["to hold", "to support", "to maintain"],
    "sugerir": ["to suggest", "to propose", "to recommend"],
    "suponer": ["to suppose", "to assume", "to presume"],
    "surgir": ["to arise", "to emerge", "to originate"],
    "sustraer": ["to subtract", "to remove", "to extract"],
    "temblar": ["to tremble", "to shake", "to quiver"],
    "tender": ["to hang", "to spread out", "to extend"],
    "tener": ["to have", "to possess", "to own"],
    "tentar": ["to tempt", "to entice", "to try"],
    "teñir": ["to dye", "to color", "to tint"],
    "torcer": ["to twist", "to bend", "to distort"],
    "tostar": ["to toast", "to roast", "to brown"],
    "tostarse": ["to get toasted", "to brown", "to crisp"],
    "traducir": ["to translate", "to render", "to interpret"],
    "traer": ["to bring", "to fetch", "to carry"],
    "transferir": ["to transfer", "to shift", "to move"],
    "tropezar": ["to stumble", "to trip", "to falter"],
    "valer": ["to be worth", "to cost", "to amount to"],
    "vencer": ["to overcome", "to defeat", "to conquer"],
    "venir": ["to come", "to approach", "to arrive"],
    "ver": ["to see", "to watch", "to observe"],
    "verter": ["to pour", "to spill", "to flow"],
    "vestir": ["to dress", "to clothe", "to attire"],
    "vestirse": ["to dress oneself", "to get dressed", "to clothe oneself"],
    "volar": ["to fly", "to soar", "to glide"],
    "volver": ["to return", "to come back", "to revisit"],
    "volverse": ["to become", "to turn (oneself)", "to change"],
    "yacer": ["to lie (recline)", "to repose", "to be situated"],
    "yuxtaponer": ["to juxtapose", "to place side by side", "to set in juxtaposition"],
}
