vb_forms_dict = {
	"abastecer_yo": "abastezco",
	"abastecer_tú": "abasteces",
	"abastecer_él/ella/usted": "abastece",
	"abastecer_nosotros/nosotras": "abastecemos",
	"abastecer_vosotros/vosotras": "abastecéis",
	"abastecer_ellos/ellas/ustedes": "abastecen",

	"absolver_yo": "absuelvo",
	"absolver_tú": "absuelves",
	"absolver_él/ella/usted": "absuelve",
	"absolver_nosotros/nosotras": "absolvemos",
	"absolver_vosotros/vosotras": "absolvéis",
	"absolver_ellos/ellas/ustedes": "absuelven",

	"abstenerse_yo": "me abstengo",
	"abstenerse_tú": "te abstienes",
	"abstenerse_él/ella/usted": "se abstiene",
	"abstenerse_nosotros/nosotras": "nos abstenemos",
	"abstenerse_vosotros/vosotras": "os abstenéis",
	"abstenerse_ellos/ellas/ustedes": "se abstienen",

	"abstraer_yo": "abstraigo",
	"abstraer_tú": "abstraes",
	"abstraer_él/ella/usted": "abstrae",
	"abstraer_nosotros/nosotras": "abstraemos",
	"abstraer_vosotros/vosotras": "abstraéis",
	"abstraer_ellos/ellas/ustedes": "abstraen",

	"acertar_yo": "acierto",
	"acertar_tú": "aciertas",
	"acertar_él/ella/usted": "acierta",
	"acertar_nosotros/nosotras": "acertamos",
	"acertar_vosotros/vosotras": "acertáis",
	"acertar_ellos/ellas/ustedes": "aciertan",

	"acoger_yo": "acojo",
	"acoger_tú": "acoges",
	"acoger_él/ella/usted": "acoge",
	"acoger_nosotros/nosotras": "acogemos",
	"acoger_vosotros/vosotras": "acogéis",
	"acoger_ellos/ellas/ustedes": "acogen",

	"acontecer_yo": "acontezco",
	"acontecer_tú": "aconteces",
	"acontecer_él/ella/usted": "acontece",
	"acontecer_nosotros/nosotras": "acontecemos",
	"acontecer_vosotros/vosotras": "acontecéis",
	"acontecer_ellos/ellas/ustedes": "acontecen",

	"acordar_yo": "acuerdo",
	"acordar_tú": "acuerdas",
	"acordar_él/ella/usted": "acuerda",
	"acordar_nosotros/nosotras": "acordamos",
	"acordar_vosotros/vosotras": "acordáis",
	"acordar_ellos/ellas/ustedes": "acuerdan",

	"acostar_yo": "acuesto",
	"acostar_tú": "acuestas",
	"acostar_él/ella/usted": "acuesta",
	"acostar_nosotros/nosotras": "acostamos",
	"acostar_vosotros/vosotras": "acostáis",
	"acostar_ellos/ellas/ustedes": "acuestan",

	"acostarse_yo": "me acuesto",
	"acostarse_tú": "te acuestas",
	"acostarse_él/ella/usted": "se acuesta",
	"acostarse_nosotros/nosotras": "nos acostamos",
	"acostarse_vosotros/vosotras": "os acostáis",
	"acostarse_ellos/ellas/ustedes": "se acuestan",

	"adherir_yo": "adhiero",
	"adherir_tú": "adhieres",
	"adherir_él/ella/usted": "adhiere",
	"adherir_nosotros/nosotras": "adherimos",
	"adherir_vosotros/vosotras": "adherís",
	"adherir_ellos/ellas/ustedes": "adhieren",

	"adormecer_yo": "adormezco",
	"adormecer_tú": "adormeces",
	"adormecer_él/ella/usted": "adormece",
	"adormecer_nosotros/nosotras": "adormecemos",
	"adormecer_vosotros/vosotras": "adormecéis",
	"adormecer_ellos/ellas/ustedes": "adormecen",

	"adquirir_yo": "adquiero",
	"adquirir_tú": "adquieres",
	"adquirir_él/ella/usted": "adquiere",
	"adquirir_nosotros/nosotras": "adquirimos",
	"adquirir_vosotros/vosotras": "adquirís",
	"adquirir_ellos/ellas/ustedes": "adquieren",

	"aducir_yo": "aduzco",
	"aducir_tú": "aduces",
	"aducir_él/ella/usted": "aduce",
	"aducir_nosotros/nosotras": "aducimos",
	"aducir_vosotros/vosotras": "aducís",
	"aducir_ellos/ellas/ustedes": "aducen",

	"advertir_yo": "advierto",
	"advertir_tú": "adviertes",
	"advertir_él/ella/usted": "advierte",
	"advertir_nosotros/nosotras": "advertimos",
	"advertir_vosotros/vosotras": "advertís",
	"advertir_ellos/ellas/ustedes": "advierten",

	"agradecer_yo": "agradezco",
	"agradecer_tú": "agradeces",
	"agradecer_él/ella/usted": "agradece",
	"agradecer_nosotros/nosotras": "agradecemos",
	"agradecer_vosotros/vosotras": "agradecéis",
	"agradecer_ellos/ellas/ustedes": "agradecen",

	"almorzar_yo": "almuerzo",
	"almorzar_tú": "almuerzas",
	"almorzar_él/ella/usted": "almuerza",
	"almorzar_nosotros/nosotras": "almorzamos",
	"almorzar_vosotros/vosotras": "almorzáis",
	"almorzar_ellos/ellas/ustedes": "almuerzan",

	"aparecer_yo": "aparezco",
	"aparecer_tú": "apareces",
	"aparecer_él/ella/usted": "aparece",
	"aparecer_nosotros/nosotras": "aparecemos",
	"aparecer_vosotros/vosotras": "aparecéis",
	"aparecer_ellos/ellas/ustedes": "aparecen",

	"apetecer_yo": "apetezco",
	"apetecer_tú": "apeteces",
	"apetecer_él/ella/usted": "apetece",
	"apetecer_nosotros/nosotras": "apetecemos",
	"apetecer_vosotros/vosotras": "apetecéis",
	"apetecer_ellos/ellas/ustedes": "apetecen",

	"apostar_yo": "apuesto",
	"apostar_tú": "apuestas",
	"apostar_él/ella/usted": "apuesta",
	"apostar_nosotros/nosotras": "apostamos",
	"apostar_vosotros/vosotras": "apostáis",
	"apostar_ellos/ellas/ustedes": "apuestan",

	"apretar_yo": "aprieto",
	"apretar_tú": "aprietas",
	"apretar_él/ella/usted": "aprieta",
	"apretar_nosotros/nosotras": "apretamos",
	"apretar_vosotros/vosotras": "apretáis",
	"apretar_ellos/ellas/ustedes": "aprietan",

	"aprobar_yo": "apruebo",
	"aprobar_tú": "apruebas",
	"aprobar_él/ella/usted": "aprueba",
	"aprobar_nosotros/nosotras": "aprobamos",
	"aprobar_vosotros/vosotras": "aprobáis",
	"aprobar_ellos/ellas/ustedes": "aprueban",

	"arrepentirse_yo": "me arrepiento",
	"arrepentirse_tú": "te arrepientes",
	"arrepentirse_él/ella/usted": "se arrepiente",
	"arrepentirse_nosotros/nosotras": "nos arrepentimos",
	"arrepentirse_vosotros/vosotras": "os arrepentís",
	"arrepentirse_ellos/ellas/ustedes": "se arrepienten",

	"ascender_yo": "asciendo",
	"ascender_tú": "asciendes",
	"ascender_él/ella/usted": "asciende",
	"ascender_nosotros/nosotras": "ascendemos",
	"ascender_vosotros/vosotras": "ascendéis",
	"ascender_ellos/ellas/ustedes": "ascienden",

	"asentir_yo": "asiento",
	"asentir_tú": "asientes",
	"asentir_él/ella/usted": "asiente",
	"asentir_nosotros/nosotras": "asentimos",
	"asentir_vosotros/vosotras": "asentís",
	"asentir_ellos/ellas/ustedes": "asienten",

	"asir_yo": "asgo",
	"asir_tú": "ases",
	"asir_él/ella/usted": "ase",
	"asir_nosotros/nosotras": "asimos",
	"asir_vosotros/vosotras": "asís",
	"asir_ellos/ellas/ustedes": "asen",

	"atenerse_yo": "me atengo",
	"atenerse_tú": "te atienes",
	"atenerse_él/ella/usted": "se atiene",
	"atenerse_nosotros/nosotras": "nos atenemos",
	"atenerse_vosotros/vosotras": "os atenéis",
	"atenerse_ellos/ellas/ustedes": "se atienen",

	"atraer_yo": "atraigo",
	"atraer_tú": "atraes",
	"atraer_él/ella/usted": "atrae",
	"atraer_nosotros/nosotras": "atraemos",
	"atraer_vosotros/vosotras": "atraéis",
	"atraer_ellos/ellas/ustedes": "atraen",

	"avenirse_yo": "me avengo",
	"avenirse_tú": "te avienes",
	"avenirse_él/ella/usted": "se aviene",
	"avenirse_nosotros/nosotras": "nos avenimos",
	"avenirse_vosotros/vosotras": "os avenís",
	"avenirse_ellos/ellas/ustedes": "se avienen",

	"avergonzar_yo": "avergüenzo",
	"avergonzar_tú": "avergüenzas",
	"avergonzar_él/ella/usted": "avergüenza",
	"avergonzar_nosotros/nosotras": "avergonzamos",
	"avergonzar_vosotros/vosotras": "avergonzáis",
	"avergonzar_ellos/ellas/ustedes": "avergüenzan",

	"avergonzarse_yo": "me avergüenzo",
	"avergonzarse_tú": "te avergüenzas",
	"avergonzarse_él/ella/usted": "se avergüenza",
	"avergonzarse_nosotros/nosotras": "nos avergonzamos",
	"avergonzarse_vosotros/vosotras": "os avergonzáis",
	"avergonzarse_ellos/ellas/ustedes": "se avergüenzan",

	"bendecir_yo": "bendigo",
	"bendecir_tú": "bendices",
	"bendecir_él/ella/usted": "bendice",
	"bendecir_nosotros/nosotras": "bendecimos",
	"bendecir_vosotros/vosotras": "bendecís",
	"bendecir_ellos/ellas/ustedes": "bendicen",

	"caber_yo": "quepo",
	"caber_tú": "cabes",
	"caber_él/ella/usted": "cabe",
	"caber_nosotros/nosotras": "cabemos",
	"caber_vosotros/vosotras": "cabéis",
	"caber_ellos/ellas/ustedes": "caben",

	"caer_yo": "caigo",
	"caer_tú": "caes",
	"caer_él/ella/usted": "cae",
	"caer_nosotros/nosotras": "caemos",
	"caer_vosotros/vosotras": "caéis",
	"caer_ellos/ellas/ustedes": "caen",

	"calentar_yo": "caliento",
	"calentar_tú": "calientas",
	"calentar_él/ella/usted": "calienta",
	"calentar_nosotros/nosotras": "calentamos",
	"calentar_vosotros/vosotras": "calentáis",
	"calentar_ellos/ellas/ustedes": "calientan",

	"carecer_yo": "carezco",
	"carecer_tú": "careces",
	"carecer_él/ella/usted": "carece",
	"carecer_nosotros/nosotras": "carecemos",
	"carecer_vosotros/vosotras": "carecéis",
	"carecer_ellos/ellas/ustedes": "carecen",

	"cegar_yo": "ciego",
	"cegar_tú": "ciegas",
	"cegar_él/ella/usted": "ciega",
	"cegar_nosotros/nosotras": "cegamos",
	"cegar_vosotros/vosotras": "cegáis",
	"cegar_ellos/ellas/ustedes": "ciegan",

	"ceñir_yo": "ciño",
	"ceñir_tú": "ciñes",
	"ceñir_él/ella/usted": "ciñe",
	"ceñir_nosotros/nosotras": "ceñimos",
	"ceñir_vosotros/vosotras": "ceñís",
	"ceñir_ellos/ellas/ustedes": "ciñen",

	"cerrar_yo": "cierro",
	"cerrar_tú": "cierras",
	"cerrar_él/ella/usted": "cierra",
	"cerrar_nosotros/nosotras": "cerramos",
	"cerrar_vosotros/vosotras": "cerráis",
	"cerrar_ellos/ellas/ustedes": "cierran",

	"cocer_yo": "cuezo",
	"cocer_tú": "cueces",
	"cocer_él/ella/usted": "cuece",
	"cocer_nosotros/nosotras": "cocemos",
	"cocer_vosotros/vosotras": "cocéis",
	"cocer_ellos/ellas/ustedes": "cuecen",

	"colar_yo": "cuelo",
	"colar_tú": "cuelas",
	"colar_él/ella/usted": "cuela",
	"colar_nosotros/nosotras": "colamos",
	"colar_vosotros/vosotras": "coláis",
	"colar_ellos/ellas/ustedes": "cuelan",

	"colarse_yo": "me cuelo",
	"colarse_tú": "te cuelas",
	"colarse_él/ella/usted": "se cuela",
	"colarse_nosotros/nosotras": "nos colamos",
	"colarse_vosotros/vosotras": "os coláis",
	"colarse_ellos/ellas/ustedes": "se cuelan",

	"colegir_yo": "colijo",
	"colegir_tú": "coliges",
	"colegir_él/ella/usted": "colige",
	"colegir_nosotros/nosotras": "colegimos",
	"colegir_vosotros/vosotras": "colegís",
	"colegir_ellos/ellas/ustedes": "coligen",

	"colgar_yo": "cuelgo",
	"colgar_tú": "cuelgas",
	"colgar_él/ella/usted": "cuelga",
	"colgar_nosotros/nosotras": "colgamos",
	"colgar_vosotros/vosotras": "colgáis",
	"colgar_ellos/ellas/ustedes": "cuelgan",

	"comenzar_yo": "comienzo",
	"comenzar_tú": "comienzas",
	"comenzar_él/ella/usted": "comienza",
	"comenzar_nosotros/nosotras": "comenzamos",
	"comenzar_vosotros/vosotras": "comenzáis",
	"comenzar_ellos/ellas/ustedes": "comienzan",

	"compadecer_yo": "compadezco",
	"compadecer_tú": "compadeces",
	"compadecer_él/ella/usted": "compadece",
	"compadecer_nosotros/nosotras": "compadecemos",
	"compadecer_vosotros/vosotras": "compadecéis",
	"compadecer_ellos/ellas/ustedes": "compadecen",

	"comparecer_yo": "comparezco",
	"comparecer_tú": "compareces",
	"comparecer_él/ella/usted": "comparece",
	"comparecer_nosotros/nosotras": "comparecemos",
	"comparecer_vosotros/vosotras": "comparecéis",
	"comparecer_ellos/ellas/ustedes": "comparecen",

	"complacer_yo": "complazco",
	"complacer_tú": "complaces",
	"complacer_él/ella/usted": "complace",
	"complacer_nosotros/nosotras": "complacemos",
	"complacer_vosotros/vosotras": "complacéis",
	"complacer_ellos/ellas/ustedes": "complacen",

	"componer_yo": "compongo",
	"componer_tú": "compones",
	"componer_él/ella/usted": "compone",
	"componer_nosotros/nosotras": "componemos",
	"componer_vosotros/vosotras": "componéis",
	"componer_ellos/ellas/ustedes": "componen",

	"comprobar_yo": "compruebo",
	"comprobar_tú": "compruebas",
	"comprobar_él/ella/usted": "comprueba",
	"comprobar_nosotros/nosotras": "comprobamos",
	"comprobar_vosotros/vosotras": "comprobáis",
	"comprobar_ellos/ellas/ustedes": "comprueban",

	"concebir_yo": "concibo",
	"concebir_tú": "concibes",
	"concebir_él/ella/usted": "concibe",
	"concebir_nosotros/nosotras": "concebimos",
	"concebir_vosotros/vosotras": "concebís",
	"concebir_ellos/ellas/ustedes": "conciben",

	"concertar_yo": "concierto",
	"concertar_tú": "conciertas",
	"concertar_él/ella/usted": "concierta",
	"concertar_nosotros/nosotras": "concertamos",
	"concertar_vosotros/vosotras": "concertáis",
	"concertar_ellos/ellas/ustedes": "conciertan",
	
	"concluir_yo": "concluyo",
	"concluir_tú": "concluyes",
	"concluir_él/ella/usted": "concluye",
	"concluir_nosotros/nosotras": "concluimos",
	"concluir_vosotros/vosotras": "concluís",
	"concluir_ellos/ellas/ustedes": "concluyen",

	"concordar_yo": "concuerdo",
	"concordar_tú": "concuerdas",
	"concordar_él/ella/usted": "concuerda",
	"concordar_nosotros/nosotras": "concordamos",
	"concordar_vosotros/vosotras": "concordáis",
	"concordar_ellos/ellas/ustedes": "concuerdan",

	"conducir_yo": "conduzco",
	"conducir_tú": "conduces",
	"conducir_él/ella/usted": "conduce",
	"conducir_nosotros/nosotras": "conducimos",
	"conducir_vosotros/vosotras": "conducís",
	"conducir_ellos/ellas/ustedes": "conducen",

	"conferir_yo": "confiero",
	"conferir_tú": "confieres",
	"conferir_él/ella/usted": "confiere",
	"conferir_nosotros/nosotras": "conferimos",
	"conferir_vosotros/vosotras": "conferís",
	"conferir_ellos/ellas/ustedes": "confieren",

	"confesar_yo": "confieso",
	"confesar_tú": "confiesas",
	"confesar_él/ella/usted": "confiesa",
	"confesar_nosotros/nosotras": "confesamos",
	"confesar_vosotros/vosotras": "confesáis",
	"confesar_ellos/ellas/ustedes": "confiesan",

	"conmover_yo": "conmuevo",
	"conmover_tú": "conmueves",
	"conmover_él/ella/usted": "conmueve",
	"conmover_nosotros/nosotras": "conmovemos",
	"conmover_vosotros/vosotras": "conmovéis",
	"conmover_ellos/ellas/ustedes": "conmueven",

	"conocer_yo": "conozco",
	"conocer_tú": "conoces",
	"conocer_él/ella/usted": "conoce",
	"conocer_nosotros/nosotras": "conocemos",
	"conocer_vosotros/vosotras": "conocéis",
	"conocer_ellos/ellas/ustedes": "conocen",

	"conseguir_yo": "consigo",
	"conseguir_tú": "consigues",
	"conseguir_él/ella/usted": "consigue",
	"conseguir_nosotros/nosotras": "conseguimos",
	"conseguir_vosotros/vosotras": "conseguís",
	"conseguir_ellos/ellas/ustedes": "consiguen",

	"consentir_yo": "consiento",
	"consentir_tú": "consientes",
	"consentir_él/ella/usted": "consiente",
	"consentir_nosotros/nosotras": "consentimos",
	"consentir_vosotros/vosotras": "consentís",
	"consentir_ellos/ellas/ustedes": "consienten",

	"consolar_yo": "consuelo",
	"consolar_tú": "consuelas",
	"consolar_él/ella/usted": "consuela",
	"consolar_nosotros/nosotras": "consolamos",
	"consolar_vosotros/vosotras": "consoláis",
	"consolar_ellos/ellas/ustedes": "consuelan",

	"construir_yo": "construyo",
	"construir_tú": "construyes",
	"construir_él/ella/usted": "construye",
	"construir_nosotros/nosotras": "construimos",
	"construir_vosotros/vosotras": "construís",
	"construir_ellos/ellas/ustedes": "construyen",

	"contar_yo": "cuento",
	"contar_tú": "cuentas",
	"contar_él/ella/usted": "cuenta",
	"contar_nosotros/nosotras": "contamos",
	"contar_vosotros/vosotras": "contáis",
	"contar_ellos/ellas/ustedes": "cuentan",

	"contender_yo": "contiendo",
	"contender_tú": "contiendes",
	"contender_él/ella/usted": "contiende",
	"contender_nosotros/nosotras": "contendemos",
	"contender_vosotros/vosotras": "contendéis",
	"contender_ellos/ellas/ustedes": "contienden",

	"contener_yo": "contengo",
	"contener_tú": "contienes",
	"contener_él/ella/usted": "contiene",
	"contener_nosotros/nosotras": "contenemos",
	"contener_vosotros/vosotras": "contenéis",
	"contener_ellos/ellas/ustedes": "contienen",

	"contradecir_yo": "contradigo",
	"contradecir_tú": "contradices",
	"contradecir_él/ella/usted": "contradice",
	"contradecir_nosotros/nosotras": "contradecimos",
	"contradecir_vosotros/vosotras": "contradecís",
	"contradecir_ellos/ellas/ustedes": "contradicen",

	"contraer_yo": "contraigo",
	"contraer_tú": "contraes",
	"contraer_él/ella/usted": "contrae",
	"contraer_nosotros/nosotras": "contraemos",
	"contraer_vosotros/vosotras": "contraéis",
	"contraer_ellos/ellas/ustedes": "contraen",

	"contravenir_yo": "contravengo",
	"contravenir_tú": "contravienes",
	"contravenir_él/ella/usted": "contraviene",
	"contravenir_nosotros/nosotras": "contravenimos",
	"contravenir_vosotros/vosotras": "contravenís",
	"contravenir_ellos/ellas/ustedes": "contravienen",

	"convenir_yo": "convengo",
	"convenir_tú": "convienes",
	"convenir_él/ella/usted": "conviene",
	"convenir_nosotros/nosotras": "convenimos",
	"convenir_vosotros/vosotras": "convenís",
	"convenir_ellos/ellas/ustedes": "convienen",

	"convertir_yo": "convierto",
	"convertir_tú": "conviertes",
	"convertir_él/ella/usted": "convierte",
	"convertir_nosotros/nosotras": "convertimos",
	"convertir_vosotros/vosotras": "convertís",
	"convertir_ellos/ellas/ustedes": "convierten",

	"convertirse_yo": "me convierto",
	"convertirse_tú": "te conviertes",
	"convertirse_él/ella/usted": "se convierte",
	"convertirse_nosotros/nosotras": "nos convertimos",
	"convertirse_vosotros/vosotras": "os convertís",
	"convertirse_ellos/ellas/ustedes": "se convierten",

	"corregir_yo": "corrijo",
	"corregir_tú": "corriges",
	"corregir_él/ella/usted": "corrige",
	"corregir_nosotros/nosotras": "corregimos",
	"corregir_vosotros/vosotras": "corregís",
	"corregir_ellos/ellas/ustedes": "corrigen",

	"costar_yo": "cuesto",
	"costar_tú": "cuestas",
	"costar_él/ella/usted": "cuesta",
	"costar_nosotros/nosotras": "costamos",
	"costar_vosotros/vosotras": "costáis",
	"costar_ellos/ellas/ustedes": "cuestan",

	"crecer_yo": "crezco",
	"crecer_tú": "creces",
	"crecer_él/ella/usted": "crece",
	"crecer_nosotros/nosotras": "crecemos",
	"crecer_vosotros/vosotras": "crecéis",
	"crecer_ellos/ellas/ustedes": "crecen",
	
	"dar_yo": "doy",
	"dar_tú": "das",
	"dar_él/ella/usted": "da",
	"dar_nosotros/nosotras": "damos",
	"dar_vosotros/vosotras": "dais",
	"dar_ellos/ellas/ustedes": "dan",

	"darse_yo": "me doy",
	"darse_tú": "te das",
	"darse_él/ella/usted": "se da",
	"darse_nosotros/nosotras": "nos damos",
	"darse_vosotros/vosotras": "os dais",
	"darse_ellos/ellas/ustedes": "se dan",

	"decaer_yo": "decaigo",
	"decaer_tú": "decaes",
	"decaer_él/ella/usted": "decae",
	"decaer_nosotros/nosotras": "decaemos",
	"decaer_vosotros/vosotras": "decaéis",
	"decaer_ellos/ellas/ustedes": "decaen",

	"decir_yo": "digo",
	"decir_tú": "dices",
	"decir_él/ella/usted": "dice",
	"decir_nosotros/nosotras": "decimos",
	"decir_vosotros/vosotras": "decís",
	"decir_ellos/ellas/ustedes": "dicen",

	"decrecer_yo": "decrezco",
	"decrecer_tú": "decreces",
	"decrecer_él/ella/usted": "decrece",
	"decrecer_nosotros/nosotras": "decrecemos",
	"decrecer_vosotros/vosotras": "decrecéis",
	"decrecer_ellos/ellas/ustedes": "decrecen",

	"deducir_yo": "deduzco",
	"deducir_tú": "deduces",
	"deducir_él/ella/usted": "deduce",
	"deducir_nosotros/nosotras": "deducimos",
	"deducir_vosotros/vosotras": "deducís",
	"deducir_ellos/ellas/ustedes": "deducen",

	"defender_yo": "defiendo",
	"defender_tú": "defiendes",
	"defender_él/ella/usted": "defiende",
	"defender_nosotros/nosotras": "defendemos",
	"defender_vosotros/vosotras": "defendéis",
	"defender_ellos/ellas/ustedes": "defienden",

	"deferir_yo": "defiero",
	"deferir_tú": "defieres",
	"deferir_él/ella/usted": "defiere",
	"deferir_nosotros/nosotras": "deferimos",
	"deferir_vosotros/vosotras": "deferís",
	"deferir_ellos/ellas/ustedes": "defieren",

	"degollar_yo": "degüello",
	"degollar_tú": "degüellas",
	"degollar_él/ella/usted": "degüella",
	"degollar_nosotros/nosotras": "degollamos",
	"degollar_vosotros/vosotras": "degolláis",
	"degollar_ellos/ellas/ustedes": "degüellan",

	"demoler_yo": "demuelo",
	"demoler_tú": "demueles",
	"demoler_él/ella/usted": "demuele",
	"demoler_nosotros/nosotras": "demolemos",
	"demoler_vosotros/vosotras": "demoléis",
	"demoler_ellos/ellas/ustedes": "demuelen",

	"demostrar_yo": "demuestro",
	"demostrar_tú": "demuestras",
	"demostrar_él/ella/usted": "demuestra",
	"demostrar_nosotros/nosotras": "demostramos",
	"demostrar_vosotros/vosotras": "demostráis",
	"demostrar_ellos/ellas/ustedes": "demuestran",

	"denegar_yo": "deniego",
	"denegar_tú": "deniegas",
	"denegar_él/ella/usted": "deniega",
	"denegar_nosotros/nosotras": "denegamos",
	"denegar_vosotros/vosotras": "denegáis",
	"denegar_ellos/ellas/ustedes": "deniegan",

	"deponer_yo": "depongo",
	"deponer_tú": "depones",
	"deponer_él/ella/usted": "depone",
	"deponer_nosotros/nosotras": "deponemos",
	"deponer_vosotros/vosotras": "deponéis",
	"deponer_ellos/ellas/ustedes": "deponen",

	"derretir_yo": "derrito",
	"derretir_tú": "derrites",
	"derretir_él/ella/usted": "derrite",
	"derretir_nosotros/nosotras": "derretimos",
	"derretir_vosotros/vosotras": "derretís",
	"derretir_ellos/ellas/ustedes": "derriten",

	"derretirse_yo": "me derrito",
	"derretirse_tú": "te derrites",
	"derretirse_él/ella/usted": "se derrite",
	"derretirse_nosotros/nosotras": "nos derretimos",
	"derretirse_vosotros/vosotras": "os derretís",
	"derretirse_ellos/ellas/ustedes": "se derriten",

	"desaparecer_yo": "desaparezco",
	"desaparecer_tú": "desapareces",
	"desaparecer_él/ella/usted": "desaparece",
	"desaparecer_nosotros/nosotras": "desaparecemos",
	"desaparecer_vosotros/vosotras": "desaparecéis",
	"desaparecer_ellos/ellas/ustedes": "desaparecen",

	"desatender_yo": "desatiendo",
	"desatender_tú": "desatiendes",
	"desatender_él/ella/usted": "desatiende",
	"desatender_nosotros/nosotras": "desatendemos",
	"desatender_vosotros/vosotras": "desatendéis",
	"desatender_ellos/ellas/ustedes": "desatienden",

	"descender_yo": "desciendo",
	"descender_tú": "desciendes",
	"descender_él/ella/usted": "desciende",
	"descender_nosotros/nosotras": "descendemos",
	"descender_vosotros/vosotras": "descendéis",
	"descender_ellos/ellas/ustedes": "descienden",

	"descomponer_yo": "descompongo",
	"descomponer_tú": "descompones",
	"descomponer_él/ella/usted": "descompone",
	"descomponer_nosotros/nosotras": "descomponemos",
	"descomponer_vosotros/vosotras": "descomponéis",
	"descomponer_ellos/ellas/ustedes": "descomponen",

	"descontar_yo": "descuento",
	"descontar_tú": "descuentas",
	"descontar_él/ella/usted": "descuenta",
	"descontar_nosotros/nosotras": "descontamos",
	"descontar_vosotros/vosotras": "descontáis",
	"descontar_ellos/ellas/ustedes": "descuentan",

	"desdecir_yo": "desdigo",
	"desdecir_tú": "desdices",
	"desdecir_él/ella/usted": "desdice",
	"desdecir_nosotros/nosotras": "desdecimos",
	"desdecir_vosotros/vosotras": "desdecís",
	"desdecir_ellos/ellas/ustedes": "desdicen",

	"deshacer_yo": "deshago",
	"deshacer_tú": "deshaces",
	"deshacer_él/ella/usted": "deshace",
	"deshacer_nosotros/nosotras": "deshacemos",
	"deshacer_vosotros/vosotras": "deshacéis",
	"deshacer_ellos/ellas/ustedes": "deshacen",

	"deshacerse_yo": "me deshago",
	"deshacerse_tú": "te deshaces",
	"deshacerse_él/ella/usted": "se deshace",
	"deshacerse_nosotros/nosotras": "nos deshacemos",
	"deshacerse_vosotros/vosotras": "os deshacéis",
	"deshacerse_ellos/ellas/ustedes": "se deshacen",

	"desobedecer_yo": "desobedezco",
	"desobedecer_tú": "desobedeces",
	"desobedecer_él/ella/usted": "desobedece",
	"desobedecer_nosotros/nosotras": "desobedecemos",
	"desobedecer_vosotros/vosotras": "desobedecéis",
	"desobedecer_ellos/ellas/ustedes": "desobedecen",

	"despedir_yo": "despido",
	"despedir_tú": "despides",
	"despedir_él/ella/usted": "despide",
	"despedir_nosotros/nosotras": "despedimos",
	"despedir_vosotros/vosotras": "despedís",
	"despedir_ellos/ellas/ustedes": "despiden",

	"despedirse_yo": "me despido",
	"despedirse_tú": "te despides",
	"despedirse_él/ella/usted": "se despide",
	"despedirse_nosotros/nosotras": "nos despedimos",
	"despedirse_vosotros/vosotras": "os despedís",
	"despedirse_ellos/ellas/ustedes": "se despiden",
	
	"despertar_yo": "despierto",
	"despertar_tú": "despiertas",
	"despertar_él/ella/usted": "despierta",
	"despertar_nosotros/nosotras": "despertamos",
	"despertar_vosotros/vosotras": "despertáis",
	"despertar_ellos/ellas/ustedes": "despiertan",

	"despertarse_yo": "me despierto",
	"despertarse_tú": "te despiertas",
	"despertarse_él/ella/usted": "se despierta",
	"despertarse_nosotros/nosotras": "nos despertamos",
	"despertarse_vosotros/vosotras": "os despertáis",
	"despertarse_ellos/ellas/ustedes": "se despiertan",

	"desteñir_yo": "destiño",
	"desteñir_tú": "destiñes",
	"desteñir_él/ella/usted": "destiñe",
	"desteñir_nosotros/nosotras": "desteñimos",
	"desteñir_vosotros/vosotras": "desteñís",
	"desteñir_ellos/ellas/ustedes": "destiñen",

	"desvanecerse_yo": "me desvanezco",
	"desvanecerse_tú": "te desvaneces",
	"desvanecerse_él/ella/usted": "se desvanece",
	"desvanecerse_nosotros/nosotras": "nos desvanecemos",
	"desvanecerse_vosotros/vosotras": "os desvanecéis",
	"desvanecerse_ellos/ellas/ustedes": "se desvanecen",

	"desvestir_yo": "desvisto",
	"desvestir_tú": "desvistes",
	"desvestir_él/ella/usted": "desviste",
	"desvestir_nosotros/nosotras": "desvestimos",
	"desvestir_vosotros/vosotras": "desvestís",
	"desvestir_ellos/ellas/ustedes": "desvisten",

	"desvestirse_yo": "me desvisto",
	"desvestirse_tú": "te desvistes",
	"desvestirse_él/ella/usted": "se desviste",
	"desvestirse_nosotros/nosotras": "nos desvestimos",
	"desvestirse_vosotros/vosotras": "os desvestís",
	"desvestirse_ellos/ellas/ustedes": "se desvisten",

	"destruir_yo": "destruyo",
	"destruir_tú": "destruyes",
	"destruir_él/ella/usted": "destruye",
	"destruir_nosotros/nosotras": "destruimos",
	"destruir_vosotros/vosotras": "destruís",
	"destruir_ellos/ellas/ustedes": "destruyen",

	"detener_yo": "detengo",
	"detener_tú": "detienes",
	"detener_él/ella/usted": "detiene",
	"detener_nosotros/nosotras": "detenemos",
	"detener_vosotros/vosotras": "detenéis",
	"detener_ellos/ellas/ustedes": "detienen",

	"detenerse_yo": "me detengo",
	"detenerse_tú": "te detienes",
	"detenerse_él/ella/usted": "se detiene",
	"detenerse_nosotros/nosotras": "nos detenemos",
	"detenerse_vosotros/vosotras": "os detenéis",
	"detenerse_ellos/ellas/ustedes": "se detienen",

	"devenir_yo": "devengo",
	"devenir_tú": "devienes",
	"devenir_él/ella/usted": "deviene",
	"devenir_nosotros/nosotras": "devenimos",
	"devenir_vosotros/vosotras": "devenís",
	"devenir_ellos/ellas/ustedes": "devienen",

	"devolver_yo": "devuelvo",
	"devolver_tú": "devuelves",
	"devolver_él/ella/usted": "devuelve",
	"devolver_nosotros/nosotras": "devolvemos",
	"devolver_vosotros/vosotras": "devolvéis",
	"devolver_ellos/ellas/ustedes": "devuelven",

	"diferir_yo": "difiero",
	"diferir_tú": "difieres",
	"diferir_él/ella/usted": "difiere",
	"diferir_nosotros/nosotras": "diferimos",
	"diferir_vosotros/vosotras": "diferís",
	"diferir_ellos/ellas/ustedes": "difieren",

	"digerir_yo": "digiero",
	"digerir_tú": "digieres",
	"digerir_él/ella/usted": "digiere",
	"digerir_nosotros/nosotras": "digerimos",
	"digerir_vosotros/vosotras": "digerís",
	"digerir_ellos/ellas/ustedes": "digieren",

	"discernir_yo": "discierno",
	"discernir_tú": "disciernes",
	"discernir_él/ella/usted": "discierne",
	"discernir_nosotros/nosotras": "discernimos",
	"discernir_vosotros/vosotras": "discernís",
	"discernir_ellos/ellas/ustedes": "disciernen",

	"disentir_yo": "disiento",
	"disentir_tú": "disientes",
	"disentir_él/ella/usted": "disiente",
	"disentir_nosotros/nosotras": "disentimos",
	"disentir_vosotros/vosotras": "disentís",
	"disentir_ellos/ellas/ustedes": "disienten",

	"disolver_yo": "disuelvo",
	"disolver_tú": "disuelves",
	"disolver_él/ella/usted": "disuelve",
	"disolver_nosotros/nosotras": "disolvemos",
	"disolver_vosotros/vosotras": "disolvéis",
	"disolver_ellos/ellas/ustedes": "disuelven",

	"disponer_yo": "dispongo",
	"disponer_tú": "dispones",
	"disponer_él/ella/usted": "dispone",
	"disponer_nosotros/nosotras": "disponemos",
	"disponer_vosotros/vosotras": "disponéis",
	"disponer_ellos/ellas/ustedes": "disponen",

	"disponerse_yo": "me dispongo",
	"disponerse_tú": "te dispones",
	"disponerse_él/ella/usted": "se dispone",
	"disponerse_nosotros/nosotras": "nos disponemos",
	"disponerse_vosotros/vosotras": "os disponéis",
	"disponerse_ellos/ellas/ustedes": "se disponen",

	"distender_yo": "distiendo",
	"distender_tú": "distiendes",
	"distender_él/ella/usted": "distiende",
	"distender_nosotros/nosotras": "distendemos",
	"distender_vosotros/vosotras": "distendéis",
	"distender_ellos/ellas/ustedes": "distienden",

	"distraer_yo": "distraigo",
	"distraer_tú": "distraes",
	"distraer_él/ella/usted": "distrae",
	"distraer_nosotros/nosotras": "distraemos",
	"distraer_vosotros/vosotras": "distraéis",
	"distraer_ellos/ellas/ustedes": "distraen",

	"distraerse_yo": "me distraigo",
	"distraerse_tú": "te distraes",
	"distraerse_él/ella/usted": "se distrae",
	"distraerse_nosotros/nosotras": "nos distraemos",
	"distraerse_vosotros/vosotras": "os distraéis",
	"distraerse_ellos/ellas/ustedes": "se distraen",

	"divertir_yo": "divierto",
	"divertir_tú": "diviertes",
	"divertir_él/ella/usted": "divierte",
	"divertir_nosotros/nosotras": "divertimos",
	"divertir_vosotros/vosotras": "divertís",
	"divertir_ellos/ellas/ustedes": "divierten",

	"divertirse_yo": "me divierto",
	"divertirse_tú": "te diviertes",
	"divertirse_él/ella/usted": "se divierte",
	"divertirse_nosotros/nosotras": "nos divertimos",
	"divertirse_vosotros/vosotras": "os divertís",
	"divertirse_ellos/ellas/ustedes": "se divierten",

	"doler_yo": "duelo",
	"doler_tú": "dueles",
	"doler_él/ella/usted": "duele",
	"doler_nosotros/nosotras": "dolemos",
	"doler_vosotros/vosotras": "doléis",
	"doler_ellos/ellas/ustedes": "duelen",

	"dormir_yo": "duermo",
	"dormir_tú": "duermes",
	"dormir_él/ella/usted": "duerme",
	"dormir_nosotros/nosotras": "dormimos",
	"dormir_vosotros/vosotras": "dormís",
	"dormir_ellos/ellas/ustedes": "duermen",

	"dormirse_yo": "me duermo",
	"dormirse_tú": "te duermes",
	"dormirse_él/ella/usted": "se duerme",
	"dormirse_nosotros/nosotras": "nos dormimos",
	"dormirse_vosotros/vosotras": "os dormís",
	"dormirse_ellos/ellas/ustedes": "se duermen",

	"elegir_yo": "elijo",
	"elegir_tú": "eliges",
	"elegir_él/ella/usted": "elige",
	"elegir_nosotros/nosotras": "elegimos",
	"elegir_vosotros/vosotras": "elegís",
	"elegir_ellos/ellas/ustedes": "eligen",

	"embellecer_yo": "embellezco",
	"embellecer_tú": "embelleces",
	"embellecer_él/ella/usted": "embellece",
	"embellecer_nosotros/nosotras": "embellecemos",
	"embellecer_vosotros/vosotras": "embellecéis",
	"embellecer_ellos/ellas/ustedes": "embellecen",

	"embestir_yo": "embisto",
	"embestir_tú": "embistes",
	"embestir_él/ella/usted": "embiste",
	"embestir_nosotros/nosotras": "embestimos",
	"embestir_vosotros/vosotras": "embestís",
	"embestir_ellos/ellas/ustedes": "embisten",

	"empezar_yo": "empiezo",
	"empezar_tú": "empiezas",
	"empezar_él/ella/usted": "empieza",
	"empezar_nosotros/nosotras": "empezamos",
	"empezar_vosotros/vosotras": "empezáis",
	"empezar_ellos/ellas/ustedes": "empiezan",

	"empobrecer_yo": "empobrezco",
	"empobrecer_tú": "empobreces",
	"empobrecer_él/ella/usted": "empobrece",
	"empobrecer_nosotros/nosotras": "empobrecemos",
	"empobrecer_vosotros/vosotras": "empobrecéis",
	"empobrecer_ellos/ellas/ustedes": "empobrecen",

	"enaltecer_yo": "enaltezco",
	"enaltecer_tú": "enalteces",
	"enaltecer_él/ella/usted": "enaltece",
	"enaltecer_nosotros/nosotras": "enaltecemos",
	"enaltecer_vosotros/vosotras": "enaltecéis",
	"enaltecer_ellos/ellas/ustedes": "enaltecen",

	"encender_yo": "enciendo",
	"encender_tú": "enciendes",
	"encender_él/ella/usted": "enciende",
	"encender_nosotros/nosotras": "encendemos",
	"encender_vosotros/vosotras": "encendéis",
	"encender_ellos/ellas/ustedes": "encienden",

	"encerrar_yo": "encierro",
	"encerrar_tú": "encierras",
	"encerrar_él/ella/usted": "encierra",
	"encerrar_nosotros/nosotras": "encerramos",
	"encerrar_vosotros/vosotras": "encerráis",
	"encerrar_ellos/ellas/ustedes": "encierran",

	"encomendar_yo": "encomiendo",
	"encomendar_tú": "encomiendas",
	"encomendar_él/ella/usted": "encomienda",
	"encomendar_nosotros/nosotras": "encomendamos",
	"encomendar_vosotros/vosotras": "encomendáis",
	"encomendar_ellos/ellas/ustedes": "encomiendan",

	"encontrar_yo": "encuentro",
	"encontrar_tú": "encuentras",
	"encontrar_él/ella/usted": "encuentra",
	"encontrar_nosotros/nosotras": "encontramos",
	"encontrar_vosotros/vosotras": "encontráis",
	"encontrar_ellos/ellas/ustedes": "encuentran",

	"encontrarse_yo": "me encuentro",
	"encontrarse_tú": "te encuentras",
	"encontrarse_él/ella/usted": "se encuentra",
	"encontrarse_nosotros/nosotras": "nos encontramos",
	"encontrarse_vosotros/vosotras": "os encontráis",
	"encontrarse_ellos/ellas/ustedes": "se encuentran",

	"enflaquecerse_yo": "me enflaquezco",
	"enflaquecerse_tú": "te enflaqueces",
	"enflaquecerse_él/ella/usted": "se enflaquece",
	"enflaquecerse_nosotros/nosotras": "nos enflaquecemos",
	"enflaquecerse_vosotros/vosotras": "os enflaquecéis",
	"enflaquecerse_ellos/ellas/ustedes": "se enflaquecen",

	"enloquecer_yo": "enloquezco",
	"enloquecer_tú": "enloqueces",
	"enloquecer_él/ella/usted": "enloquece",
	"enloquecer_nosotros/nosotras": "enloquecemos",
	"enloquecer_vosotros/vosotras": "enloquecéis",
	"enloquecer_ellos/ellas/ustedes": "enloquecen",

	"enmendar_yo": "enmiendo",
	"enmendar_tú": "enmiendas",
	"enmendar_él/ella/usted": "enmienda",
	"enmendar_nosotros/nosotras": "enmendamos",
	"enmendar_vosotros/vosotras": "enmendáis",
	"enmendar_ellos/ellas/ustedes": "enmiendan",

	"enriquecer_yo": "enriquezco",
	"enriquecer_tú": "enriqueces",
	"enriquecer_él/ella/usted": "enriquece",
	"enriquecer_nosotros/nosotras": "enriquecemos",
	"enriquecer_vosotros/vosotras": "enriquecéis",
	"enriquecer_ellos/ellas/ustedes": "enriquecen",

	"enriquecerse_yo": "me enriquezco",
	"enriquecerse_tú": "te enriqueces",
	"enriquecerse_él/ella/usted": "se enriquece",
	"enriquecerse_nosotros/nosotras": "nos enriquecemos",
	"enriquecerse_vosotros/vosotras": "os enriquecéis",
	"enriquecerse_ellos/ellas/ustedes": "se enriquecen",

	"ensordecer_yo": "ensordezco",
	"ensordecer_tú": "ensordeces",
	"ensordecer_él/ella/usted": "ensordece",
	"ensordecer_nosotros/nosotras": "ensordecemos",
	"ensordecer_vosotros/vosotras": "ensordecéis",
	"ensordecer_ellos/ellas/ustedes": "ensordecen",

	"entender_yo": "entiendo",
	"entender_tú": "entiendes",
	"entender_él/ella/usted": "entiende",
	"entender_nosotros/nosotras": "entendemos",
	"entender_vosotros/vosotras": "entendéis",
	"entender_ellos/ellas/ustedes": "entienden",

	"enterrar_yo": "entierro",
	"enterrar_tú": "entierras",
	"enterrar_él/ella/usted": "entierra",
	"enterrar_nosotros/nosotras": "enterramos",
	"enterrar_vosotros/vosotras": "enterráis",
	"enterrar_ellos/ellas/ustedes": "entierran",

	"entretener_yo": "entretengo",
	"entretener_tú": "entretienes",
	"entretener_él/ella/usted": "entretiene",
	"entretener_nosotros/nosotras": "entretenemos",
	"entretener_vosotros/vosotras": "entretenéis",
	"entretener_ellos/ellas/ustedes": "entretienen",

	"entretenerse_yo": "me entretengo",
	"entretenerse_tú": "te entretienes",
	"entretenerse_él/ella/usted": "se entretiene",
	"entretenerse_nosotros/nosotras": "nos entretenemos",
	"entretenerse_vosotros/vosotras": "os entretenéis",
	"entretenerse_ellos/ellas/ustedes": "se entretienen",

	"entrever_yo": "entreveo",
	"entrever_tú": "entrevés",
	"entrever_él/ella/usted": "entrevé",
	"entrever_nosotros/nosotras": "entrevemos",
	"entrever_vosotros/vosotras": "entrevéis",
	"entrever_ellos/ellas/ustedes": "entrevén",

	"entristecer_yo": "entristezco",
	"entristecer_tú": "entristeces",
	"entristecer_él/ella/usted": "entristece",
	"entristecer_nosotros/nosotras": "entristecemos",
	"entristecer_vosotros/vosotras": "entristecéis",
	"entristecer_ellos/ellas/ustedes": "entristecen",

	"envejecer_yo": "envejezco",
	"envejecer_tú": "envejeces",
	"envejecer_él/ella/usted": "envejece",
	"envejecer_nosotros/nosotras": "envejecemos",
	"envejecer_vosotros/vosotras": "envejecéis",
	"envejecer_ellos/ellas/ustedes": "envejecen",

	"envolver_yo": "envuelvo",
	"envolver_tú": "envuelves",
	"envolver_él/ella/usted": "envuelve",
	"envolver_nosotros/nosotras": "envolvemos",
	"envolver_vosotros/vosotras": "envolvéis",
	"envolver_ellos/ellas/ustedes": "envuelven",

	"equivaler_yo": "equivalgo",
	"equivaler_tú": "equivales",
	"equivaler_él/ella/usted": "equivale",
	"equivaler_nosotros/nosotras": "equivalemos",
	"equivaler_vosotros/vosotras": "equivaléis",
	"equivaler_ellos/ellas/ustedes": "equivalen",

	"erguir_yo": "yergo",
	"erguir_tú": "yergues",
	"erguir_él/ella/usted": "yergue",
	"erguir_nosotros/nosotras": "erguimos",
	"erguir_vosotros/vosotras": "erguís",
	"erguir_ellos/ellas/ustedes": "yerguen",

	"esclarecer_yo": "esclarezco",
	"esclarecer_tú": "esclareces",
	"esclarecer_él/ella/usted": "esclarece",
	"esclarecer_nosotros/nosotras": "esclarecemos",
	"esclarecer_vosotros/vosotras": "esclarecéis",
	"esclarecer_ellos/ellas/ustedes": "esclarecen",

	"escoger_yo": "escojo",
	"escoger_tú": "escoges",
	"escoger_él/ella/usted": "escoge",
	"escoger_nosotros/nosotras": "escogemos",
	"escoger_vosotros/vosotras": "escogéis",
	"escoger_ellos/ellas/ustedes": "escogen",

	"establecer_yo": "establezco",
	"establecer_tú": "estableces",
	"establecer_él/ella/usted": "establece",
	"establecer_nosotros/nosotras": "establecemos",
	"establecer_vosotros/vosotras": "establecéis",
	"establecer_ellos/ellas/ustedes": "establecen",

	"estar_yo": "estoy",
	"estar_tú": "estás",
	"estar_él/ella/usted": "está",
	"estar_nosotros/nosotras": "estamos",
	"estar_vosotros/vosotras": "estáis",
	"estar_ellos/ellas/ustedes": "están",

	"estremecer_yo": "estremezco",
	"estremecer_tú": "estremeces",
	"estremecer_él/ella/usted": "estremece",
	"estremecer_nosotros/nosotras": "estremecemos",
	"estremecer_vosotros/vosotras": "estremecéis",
	"estremecer_ellos/ellas/ustedes": "estremecen",

	"exponer_yo": "expongo",
	"exponer_tú": "expones",
	"exponer_él/ella/usted": "expone",
	"exponer_nosotros/nosotras": "exponemos",
	"exponer_vosotros/vosotras": "exponéis",
	"exponer_ellos/ellas/ustedes": "exponen",

	"extender_yo": "extiendo",
	"extender_tú": "extiendes",
	"extender_él/ella/usted": "extiende",
	"extender_nosotros/nosotras": "extendemos",
	"extender_vosotros/vosotras": "extendéis",
	"extender_ellos/ellas/ustedes": "extienden",

	"extraer_yo": "extraigo",
	"extraer_tú": "extraes",
	"extraer_él/ella/usted": "extrae",
	"extraer_nosotros/nosotras": "extraemos",
	"extraer_vosotros/vosotras": "extraéis",
	"extraer_ellos/ellas/ustedes": "extraen",
	
	"fallecer_yo": "fallezco",
	"fallecer_tú": "falleces",
	"fallecer_él/ella/usted": "fallece",
	"fallecer_nosotros/nosotras": "fallecemos",
	"fallecer_vosotros/vosotras": "fallecéis",
	"fallecer_ellos/ellas/ustedes": "fallecen",

	"favorecer_yo": "favorezco",
	"favorecer_tú": "favoreces",
	"favorecer_él/ella/usted": "favorece",
	"favorecer_nosotros/nosotras": "favorecemos",
	"favorecer_vosotros/vosotras": "favorecéis",
	"favorecer_ellos/ellas/ustedes": "favorecen",

	"fingir_yo": "finjo",
	"fingir_tú": "finges",
	"fingir_él/ella/usted": "finge",
	"fingir_nosotros/nosotras": "fingimos",
	"fingir_vosotros/vosotras": "fingís",
	"fingir_ellos/ellas/ustedes": "fingen",

	"florecer_yo": "florezco",
	"florecer_tú": "floreces",
	"florecer_él/ella/usted": "florece",
	"florecer_nosotros/nosotras": "florecemos",
	"florecer_vosotros/vosotras": "florecéis",
	"florecer_ellos/ellas/ustedes": "florecen",

	"fortalecer_yo": "fortalezco",
	"fortalecer_tú": "fortaleces",
	"fortalecer_él/ella/usted": "fortalece",
	"fortalecer_nosotros/nosotras": "fortalecemos",
	"fortalecer_vosotros/vosotras": "fortalecéis",
	"fortalecer_ellos/ellas/ustedes": "fortalecen",

	"freír_yo": "frío",
	"freír_tú": "fríes",
	"freír_él/ella/usted": "fríe",
	"freír_nosotros/nosotras": "freímos",
	"freír_vosotros/vosotras": "freís",
	"freír_ellos/ellas/ustedes": "fríen",

	"fluir_yo": "fluyo",
	"fluir_tú": "fluyes",
	"fluir_él/ella/usted": "fluye",
	"fluir_nosotros/nosotras": "fluimos",
	"fluir_vosotros/vosotras": "fluís",
	"fluir_ellos/ellas/ustedes": "fluyen",

	"gemir_yo": "gimo",
	"gemir_tú": "gimes",
	"gemir_él/ella/usted": "gime",
	"gemir_nosotros/nosotras": "gemimos",
	"gemir_vosotros/vosotras": "gemís",
	"gemir_ellos/ellas/ustedes": "gimen",

	"gobernar_yo": "gobierno",
	"gobernar_tú": "gobiernas",
	"gobernar_él/ella/usted": "gobierna",
	"gobernar_nosotros/nosotras": "gobernamos",
	"gobernar_vosotros/vosotras": "gobernáis",
	"gobernar_ellos/ellas/ustedes": "gobiernan",

	"guarnecer_yo": "guarnezco",
	"guarnecer_tú": "guarneces",
	"guarnecer_él/ella/usted": "guarnece",
	"guarnecer_nosotros/nosotras": "guarnecemos",
	"guarnecer_vosotros/vosotras": "guarnecéis",
	"guarnecer_ellos/ellas/ustedes": "guarnecen",

	"haber_yo": "he",
	"haber_tú": "has",
	"haber_él/ella/usted": "ha",
	"haber_nosotros/nosotras": "hemos",
	"haber_vosotros/vosotras": "habéis",
	"haber_ellos/ellas/ustedes": "han",

	"hacer_yo": "hago",
	"hacer_tú": "haces",
	"hacer_él/ella/usted": "hace",
	"hacer_nosotros/nosotras": "hacemos",
	"hacer_vosotros/vosotras": "hacéis",
	"hacer_ellos/ellas/ustedes": "hacen",

	"hacerse_yo": "me hago",
	"hacerse_tú": "te haces",
	"hacerse_él/ella/usted": "se hace",
	"hacerse_nosotros/nosotras": "nos hacemos",
	"hacerse_vosotros/vosotras": "os hacéis",
	"hacerse_ellos/ellas/ustedes": "se hacen",

	"henchir_yo": "hincho",
	"henchir_tú": "hinches",
	"henchir_él/ella/usted": "hinche",
	"henchir_nosotros/nosotras": "henchimos",
	"henchir_vosotros/vosotras": "henchís",
	"henchir_ellos/ellas/ustedes": "hinchen",

	"hender_yo": "hiendo",
	"hender_tú": "hiendes",
	"hender_él/ella/usted": "hiende",
	"hender_nosotros/nosotras": "hendemos",
	"hender_vosotros/vosotras": "hendéis",
	"hender_ellos/ellas/ustedes": "hienden",

	"herir_yo": "hiero",
	"herir_tú": "hieres",
	"herir_él/ella/usted": "hiere",
	"herir_nosotros/nosotras": "herimos",
	"herir_vosotros/vosotras": "herís",
	"herir_ellos/ellas/ustedes": "hieren",

	"herrar_yo": "hierro",
	"herrar_tú": "hierras",
	"herrar_él/ella/usted": "hierra",
	"herrar_nosotros/nosotras": "herramos",
	"herrar_vosotros/vosotras": "herráis",
	"herrar_ellos/ellas/ustedes": "hierran",

	"hervir_yo": "hiervo",
	"hervir_tú": "hierves",
	"hervir_él/ella/usted": "hierve",
	"hervir_nosotros/nosotras": "hervimos",
	"hervir_vosotros/vosotras": "hervís",
	"hervir_ellos/ellas/ustedes": "hierven",

	"huir_yo": "huyo",
	"huir_tú": "huyes",
	"huir_él/ella/usted": "huye",
	"huir_nosotros/nosotras": "huimos",
	"huir_vosotros/vosotras": "huís",
	"huir_ellos/ellas/ustedes": "huyen",

	"humedecer_yo": "humedezco",
	"humedecer_tú": "humedeces",
	"humedecer_él/ella/usted": "humedece",
	"humedecer_nosotros/nosotras": "humedecemos",
	"humedecer_vosotros/vosotras": "humedecéis",
	"humedecer_ellos/ellas/ustedes": "humedecen",
	
	"impedir_yo": "impido",
	"impedir_tú": "impides",
	"impedir_él/ella/usted": "impide",
	"impedir_nosotros/nosotras": "impedimos",
	"impedir_vosotros/vosotras": "impedís",
	"impedir_ellos/ellas/ustedes": "impiden",

	"imponer_yo": "impongo",
	"imponer_tú": "impones",
	"imponer_él/ella/usted": "impone",
	"imponer_nosotros/nosotras": "imponemos",
	"imponer_vosotros/vosotras": "imponéis",
	"imponer_ellos/ellas/ustedes": "imponen",

	"inducir_yo": "induzco",
	"inducir_tú": "induces",
	"inducir_él/ella/usted": "induce",
	"inducir_nosotros/nosotras": "inducimos",
	"inducir_vosotros/vosotras": "inducís",
	"inducir_ellos/ellas/ustedes": "inducen",

	"inferir_yo": "infiero",
	"inferir_tú": "infieres",
	"inferir_él/ella/usted": "infiere",
	"inferir_nosotros/nosotras": "inferimos",
	"inferir_vosotros/vosotras": "inferís",
	"inferir_ellos/ellas/ustedes": "infieren",

	"ingerir_yo": "ingiero",
	"ingerir_tú": "ingieres",
	"ingerir_él/ella/usted": "ingiere",
	"ingerir_nosotros/nosotras": "ingerimos",
	"ingerir_vosotros/vosotras": "ingerís",
	"ingerir_ellos/ellas/ustedes": "ingieren",

	"inquirir_yo": "inquiero",
	"inquirir_tú": "inquieres",
	"inquirir_él/ella/usted": "inquiere",
	"inquirir_nosotros/nosotras": "inquirimos",
	"inquirir_vosotros/vosotras": "inquirís",
	"inquirir_ellos/ellas/ustedes": "inquieren",

	"interferir_yo": "interfiero",
	"interferir_tú": "interfieres",
	"interferir_él/ella/usted": "interfiere",
	"interferir_nosotros/nosotras": "interferimos",
	"interferir_vosotros/vosotras": "interferís",
	"interferir_ellos/ellas/ustedes": "interfieren",

	"interponer_yo": "interpongo",
	"interponer_tú": "interpones",
	"interponer_él/ella/usted": "interpone",
	"interponer_nosotros/nosotras": "interponemos",
	"interponer_vosotros/vosotras": "interponéis",
	"interponer_ellos/ellas/ustedes": "interponen",

	"intervenir_yo": "intervengo",
	"intervenir_tú": "intervienes",
	"intervenir_él/ella/usted": "interviene",
	"intervenir_nosotros/nosotras": "intervenimos",
	"intervenir_vosotros/vosotras": "intervenís",
	"intervenir_ellos/ellas/ustedes": "intervienen",

	"introducir_yo": "introduzco",
	"introducir_tú": "introduces",
	"introducir_él/ella/usted": "introduce",
	"introducir_nosotros/nosotras": "introducimos",
	"introducir_vosotros/vosotras": "introducís",
	"introducir_ellos/ellas/ustedes": "introducen",

	"invertir_yo": "invierto",
	"invertir_tú": "inviertes",
	"invertir_él/ella/usted": "invierte",
	"invertir_nosotros/nosotras": "invertimos",
	"invertir_vosotros/vosotras": "invertís",
	"invertir_ellos/ellas/ustedes": "invierten",

	"ir_yo": "voy",
	"ir_tú": "vas",
	"ir_él/ella/usted": "va",
	"ir_nosotros/nosotras": "vamos",
	"ir_vosotros/vosotras": "vais",
	"ir_ellos/ellas/ustedes": "van",

	"irse_yo": "me voy",
	"irse_tú": "te vas",
	"irse_él/ella/usted": "se va",
	"irse_nosotros/nosotras": "nos vamos",
	"irse_vosotros/vosotras": "os vais",
	"irse_ellos/ellas/ustedes": "se van",

	"jugar_yo": "juego",
	"jugar_tú": "juegas",
	"jugar_él/ella/usted": "juega",
	"jugar_nosotros/nosotras": "jugamos",
	"jugar_vosotros/vosotras": "jugáis",
	"jugar_ellos/ellas/ustedes": "juegan",

	"lucir_yo": "luzco",
	"lucir_tú": "luces",
	"lucir_él/ella/usted": "luce",
	"lucir_nosotros/nosotras": "lucimos",
	"lucir_vosotros/vosotras": "lucís",
	"lucir_ellos/ellas/ustedes": "lucen",

	"maldecir_yo": "maldigo",
	"maldecir_tú": "maldices",
	"maldecir_él/ella/usted": "maldice",
	"maldecir_nosotros/nosotras": "maldecimos",
	"maldecir_vosotros/vosotras": "maldecís",
	"maldecir_ellos/ellas/ustedes": "maldicen",

	"malquerer_yo": "malquiero",
	"malquerer_tú": "malquieres",
	"malquerer_él/ella/usted": "malquiere",
	"malquerer_nosotros/nosotras": "malqueremos",
	"malquerer_vosotros/vosotras": "malqueréis",
	"malquerer_ellos/ellas/ustedes": "malquieren",
	
	"mantener_yo": "mantengo",
	"mantener_tú": "mantienes",
	"mantener_él/ella/usted": "mantiene",
	"mantener_nosotros/nosotras": "mantenemos",
	"mantener_vosotros/vosotras": "mantenéis",
	"mantener_ellos/ellas/ustedes": "mantienen",

	"mantenerse_yo": "me mantengo",
	"mantenerse_tú": "te mantienes",
	"mantenerse_él/ella/usted": "se mantiene",
	"mantenerse_nosotros/nosotras": "nos mantenemos",
	"mantenerse_vosotros/vosotras": "os mantenéis",
	"mantenerse_ellos/ellas/ustedes": "se mantienen",

	"mecer_yo": "mezo",
	"mecer_tú": "meces",
	"mecer_él/ella/usted": "mece",
	"mecer_nosotros/nosotras": "mecemos",
	"mecer_vosotros/vosotras": "mecéis",
	"mecer_ellos/ellas/ustedes": "mecen",

	"medir_yo": "mido",
	"medir_tú": "mides",
	"medir_él/ella/usted": "mide",
	"medir_nosotros/nosotras": "medimos",
	"medir_vosotros/vosotras": "medís",
	"medir_ellos/ellas/ustedes": "miden",

	"mentir_yo": "miento",
	"mentir_tú": "mientes",
	"mentir_él/ella/usted": "miente",
	"mentir_nosotros/nosotras": "mentimos",
	"mentir_vosotros/vosotras": "mentís",
	"mentir_ellos/ellas/ustedes": "mienten",

	"merecer_yo": "merezco",
	"merecer_tú": "mereces",
	"merecer_él/ella/usted": "merece",
	"merecer_nosotros/nosotras": "merecemos",
	"merecer_vosotros/vosotras": "merecéis",
	"merecer_ellos/ellas/ustedes": "merecen",

	"moler_yo": "muelo",
	"moler_tú": "mueles",
	"moler_él/ella/usted": "muele",
	"moler_nosotros/nosotras": "molemos",
	"moler_vosotros/vosotras": "moléis",
	"moler_ellos/ellas/ustedes": "muelen",

	"morder_yo": "muerdo",
	"morder_tú": "muerdes",
	"morder_él/ella/usted": "muerde",
	"morder_nosotros/nosotras": "mordemos",
	"morder_vosotros/vosotras": "mordéis",
	"morder_ellos/ellas/ustedes": "muerden",

	"morir_yo": "muero",
	"morir_tú": "mueres",
	"morir_él/ella/usted": "muere",
	"morir_nosotros/nosotras": "morimos",
	"morir_vosotros/vosotras": "morís",
	"morir_ellos/ellas/ustedes": "mueren",

	"morirse_yo": "me muero",
	"morirse_tú": "te mueres",
	"morirse_él/ella/usted": "se muere",
	"morirse_nosotros/nosotras": "nos morimos",
	"morirse_vosotros/vosotras": "os morís",
	"morirse_ellos/ellas/ustedes": "se mueren",

	"mostrar_yo": "muestro",
	"mostrar_tú": "muestras",
	"mostrar_él/ella/usted": "muestra",
	"mostrar_nosotros/nosotras": "mostramos",
	"mostrar_vosotros/vosotras": "mostráis",
	"mostrar_ellos/ellas/ustedes": "muestran",

	"mostrarse_yo": "me muestro",
	"mostrarse_tú": "te muestras",
	"mostrarse_él/ella/usted": "se muestra",
	"mostrarse_nosotros/nosotras": "nos mostramos",
	"mostrarse_vosotros/vosotras": "os mostráis",
	"mostrarse_ellos/ellas/ustedes": "se muestran",

	"mover_yo": "muevo",
	"mover_tú": "mueves",
	"mover_él/ella/usted": "mueve",
	"mover_nosotros/nosotras": "movemos",
	"mover_vosotros/vosotras": "movéis",
	"mover_ellos/ellas/ustedes": "mueven",

	"moverse_yo": "me muevo",
	"moverse_tú": "te mueves",
	"moverse_él/ella/usted": "se mueve",
	"moverse_nosotros/nosotras": "nos movemos",
	"moverse_vosotros/vosotras": "os movéis",
	"moverse_ellos/ellas/ustedes": "se mueven",

	"nacer_yo": "nazco",
	"nacer_tú": "naces",
	"nacer_él/ella/usted": "nace",
	"nacer_nosotros/nosotras": "nacemos",
	"nacer_vosotros/vosotras": "nacéis",
	"nacer_ellos/ellas/ustedes": "nacen",

	"negar_yo": "niego",
	"negar_tú": "niegas",
	"negar_él/ella/usted": "niega",
	"negar_nosotros/nosotras": "negamos",
	"negar_vosotros/vosotras": "negáis",
	"negar_ellos/ellas/ustedes": "niegan",

	"negarse_yo": "me niego",
	"negarse_tú": "te niegas",
	"negarse_él/ella/usted": "se niega",
	"negarse_nosotros/nosotras": "nos negamos",
	"negarse_vosotros/vosotras": "os negáis",
	"negarse_ellos/ellas/ustedes": "se niegan",

	"obedecer_yo": "obedezco",
	"obedecer_tú": "obedeces",
	"obedecer_él/ella/usted": "obedece",
	"obedecer_nosotros/nosotras": "obedecemos",
	"obedecer_vosotros/vosotras": "obedecéis",
	"obedecer_ellos/ellas/ustedes": "obedecen",

	"obtener_yo": "obtengo",
	"obtener_tú": "obtienes",
	"obtener_él/ella/usted": "obtiene",
	"obtener_nosotros/nosotras": "obtenemos",
	"obtener_vosotros/vosotras": "obtenéis",
	"obtener_ellos/ellas/ustedes": "obtienen",

	"ofrecer_yo": "ofrezco",
	"ofrecer_tú": "ofreces",
	"ofrecer_él/ella/usted": "ofrece",
	"ofrecer_nosotros/nosotras": "ofrecemos",
	"ofrecer_vosotros/vosotras": "ofrecéis",
	"ofrecer_ellos/ellas/ustedes": "ofrecen",

	"oír_yo": "oigo",
	"oír_tú": "oyes",
	"oír_él/ella/usted": "oye",
	"oír_nosotros/nosotras": "oímos",
	"oír_vosotros/vosotras": "oís",
	"oír_ellos/ellas/ustedes": "oyen",

	"oler_yo": "huelo",
	"oler_tú": "hueles",
	"oler_él/ella/usted": "huele",
	"oler_nosotros/nosotras": "olemos",
	"oler_vosotros/vosotras": "oléis",
	"oler_ellos/ellas/ustedes": "huelen",

	"oponer_yo": "opongo",
	"oponer_tú": "opones",
	"oponer_él/ella/usted": "opone",
	"oponer_nosotros/nosotras": "oponemos",
	"oponer_vosotros/vosotras": "oponéis",
	"oponer_ellos/ellas/ustedes": "oponen",

	"oponerse_yo": "me opongo",
	"oponerse_tú": "te opones",
	"oponerse_él/ella/usted": "se opone",
	"oponerse_nosotros/nosotras": "nos oponemos",
	"oponerse_vosotros/vosotras": "os oponéis",
	"oponerse_ellos/ellas/ustedes": "se oponen",

	"padecer_yo": "padezco",
	"padecer_tú": "padeces",
	"padecer_él/ella/usted": "padece",
	"padecer_nosotros/nosotras": "padecemos",
	"padecer_vosotros/vosotras": "padecéis",
	"padecer_ellos/ellas/ustedes": "padecen",

	"parecer_yo": "parezco",
	"parecer_tú": "pareces",
	"parecer_él/ella/usted": "parece",
	"parecer_nosotros/nosotras": "parecemos",
	"parecer_vosotros/vosotras": "parecéis",
	"parecer_ellos/ellas/ustedes": "parecen",

	"parecerse_yo": "me parezco",
	"parecerse_tú": "te pareces",
	"parecerse_él/ella/usted": "se parece",
	"parecerse_nosotros/nosotras": "nos parecemos",
	"parecerse_vosotros/vosotras": "os parecéis",
	"parecerse_ellos/ellas/ustedes": "se parecen",

	"pedir_yo": "pido",
	"pedir_tú": "pides",
	"pedir_él/ella/usted": "pide",
	"pedir_nosotros/nosotras": "pedimos",
	"pedir_vosotros/vosotras": "pedís",
	"pedir_ellos/ellas/ustedes": "piden",

	"pensar_yo": "pienso",
	"pensar_tú": "piensas",
	"pensar_él/ella/usted": "piensa",
	"pensar_nosotros/nosotras": "pensamos",
	"pensar_vosotros/vosotras": "pensáis",
	"pensar_ellos/ellas/ustedes": "piensan",

	"perder_yo": "pierdo",
	"perder_tú": "pierdes",
	"perder_él/ella/usted": "pierde",
	"perder_nosotros/nosotras": "perdemos",
	"perder_vosotros/vosotras": "perdéis",
	"perder_ellos/ellas/ustedes": "pierden",

	"perecer_yo": "perezco",
	"perecer_tú": "pereces",
	"perecer_él/ella/usted": "perece",
	"perecer_nosotros/nosotras": "perecemos",
	"perecer_vosotros/vosotras": "perecéis",
	"perecer_ellos/ellas/ustedes": "perecen",

	"permanecer_yo": "permanezco",
	"permanecer_tú": "permaneces",
	"permanecer_él/ella/usted": "permanece",
	"permanecer_nosotros/nosotras": "permanecemos",
	"permanecer_vosotros/vosotras": "permanecéis",
	"permanecer_ellos/ellas/ustedes": "permanecen",

	"perseguir_yo": "persigo",
	"perseguir_tú": "persigues",
	"perseguir_él/ella/usted": "persigue",
	"perseguir_nosotros/nosotras": "perseguimos",
	"perseguir_vosotros/vosotras": "perseguís",
	"perseguir_ellos/ellas/ustedes": "persiguen",

	"pertenecer_yo": "pertenezco",
	"pertenecer_tú": "perteneces",
	"pertenecer_él/ella/usted": "pertenece",
	"pertenecer_nosotros/nosotras": "pertenecemos",
	"pertenecer_vosotros/vosotras": "pertenecéis",
	"pertenecer_ellos/ellas/ustedes": "pertenecen",

	"pervertir_yo": "pervierto",
	"pervertir_tú": "perviertes",
	"pervertir_él/ella/usted": "pervierte",
	"pervertir_nosotros/nosotras": "pervertimos",
	"pervertir_vosotros/vosotras": "pervertís",
	"pervertir_ellos/ellas/ustedes": "pervierten",

	"placer_yo": "plazco",
	"placer_tú": "places",
	"placer_él/ella/usted": "place",
	"placer_nosotros/nosotras": "placemos",
	"placer_vosotros/vosotras": "placéis",
	"placer_ellos/ellas/ustedes": "placen",

	"plegar_yo": "pliego",
	"plegar_tú": "pliegas",
	"plegar_él/ella/usted": "pliega",
	"plegar_nosotros/nosotras": "plegamos",
	"plegar_vosotros/vosotras": "plegáis",
	"plegar_ellos/ellas/ustedes": "pliegan",

	"poder_yo": "puedo",
	"poder_tú": "puedes",
	"poder_él/ella/usted": "puede",
	"poder_nosotros/nosotras": "podemos",
	"poder_vosotros/vosotras": "podéis",
	"poder_ellos/ellas/ustedes": "pueden",

	"poner_yo": "pongo",
	"poner_tú": "pones",
	"poner_él/ella/usted": "pone",
	"poner_nosotros/nosotras": "ponemos",
	"poner_vosotros/vosotras": "ponéis",
	"poner_ellos/ellas/ustedes": "ponen",

	"ponerse_yo": "me pongo",
	"ponerse_tú": "te pones",
	"ponerse_él/ella/usted": "se pone",
	"ponerse_nosotros/nosotras": "nos ponemos",
	"ponerse_vosotros/vosotras": "os ponéis",
	"ponerse_ellos/ellas/ustedes": "se ponen",

	"posponer_yo": "pospongo",
	"posponer_tú": "pospones",
	"posponer_él/ella/usted": "pospone",
	"posponer_nosotros/nosotras": "posponemos",
	"posponer_vosotros/vosotras": "posponéis",
	"posponer_ellos/ellas/ustedes": "posponen",

	"predecir_yo": "predigo",
	"predecir_tú": "predices",
	"predecir_él/ella/usted": "predice",
	"predecir_nosotros/nosotras": "predecimos",
	"predecir_vosotros/vosotras": "predecís",
	"predecir_ellos/ellas/ustedes": "predicen",

	"predisponer_yo": "predispongo",
	"predisponer_tú": "predispones",
	"predisponer_él/ella/usted": "predispone",
	"predisponer_nosotros/nosotras": "predisponemos",
	"predisponer_vosotros/vosotras": "predisponéis",
	"predisponer_ellos/ellas/ustedes": "predisponen",

	"preferir_yo": "prefiero",
	"preferir_tú": "prefieres",
	"preferir_él/ella/usted": "prefiere",
	"preferir_nosotros/nosotras": "preferimos",
	"preferir_vosotros/vosotras": "preferís",
	"preferir_ellos/ellas/ustedes": "prefieren",

	"presentir_yo": "presiento",
	"presentir_tú": "presientes",
	"presentir_él/ella/usted": "presiente",
	"presentir_nosotros/nosotras": "presentimos",
	"presentir_vosotros/vosotras": "presentís",
	"presentir_ellos/ellas/ustedes": "presienten",

	"presuponer_yo": "presupongo",
	"presuponer_tú": "presupones",
	"presuponer_él/ella/usted": "presupone",
	"presuponer_nosotros/nosotras": "presuponemos",
	"presuponer_vosotros/vosotras": "presuponéis",
	"presuponer_ellos/ellas/ustedes": "presuponen",

	"prevalecer_yo": "prevalezco",
	"prevalecer_tú": "prevaleces",
	"prevalecer_él/ella/usted": "prevalece",
	"prevalecer_nosotros/nosotras": "prevalecemos",
	"prevalecer_vosotros/vosotras": "prevalecéis",
	"prevalecer_ellos/ellas/ustedes": "prevalecen",

	"prevenir_yo": "prevengo",
	"prevenir_tú": "previenes",
	"prevenir_él/ella/usted": "previene",
	"prevenir_nosotros/nosotras": "prevenimos",
	"prevenir_vosotros/vosotras": "prevenís",
	"prevenir_ellos/ellas/ustedes": "previenen",

	"prever_yo": "preveo",
	"prever_tú": "prevés",
	"prever_él/ella/usted": "prevé",
	"prever_nosotros/nosotras": "prevemos",
	"prever_vosotros/vosotras": "prevéis",
	"prever_ellos/ellas/ustedes": "prevén",

	"probar_yo": "pruebo",
	"probar_tú": "pruebas",
	"probar_él/ella/usted": "prueba",
	"probar_nosotros/nosotras": "probamos",
	"probar_vosotros/vosotras": "probáis",
	"probar_ellos/ellas/ustedes": "prueban",

	"probarse_yo": "me pruebo",
	"probarse_tú": "te pruebas",
	"probarse_él/ella/usted": "se prueba",
	"probarse_nosotros/nosotras": "nos probamos",
	"probarse_vosotros/vosotras": "os probáis",
	"probarse_ellos/ellas/ustedes": "se prueban",

	"producir_yo": "produzco",
	"producir_tú": "produces",
	"producir_él/ella/usted": "produce",
	"producir_nosotros/nosotras": "producimos",
	"producir_vosotros/vosotras": "producís",
	"producir_ellos/ellas/ustedes": "producen",

	"proferir_yo": "profiero",
	"proferir_tú": "profieres",
	"proferir_él/ella/usted": "profiere",
	"proferir_nosotros/nosotras": "proferimos",
	"proferir_vosotros/vosotras": "proferís",
	"proferir_ellos/ellas/ustedes": "profieren",

	"promover_yo": "promuevo",
	"promover_tú": "promueves",
	"promover_él/ella/usted": "promueve",
	"promover_nosotros/nosotras": "promovemos",
	"promover_vosotros/vosotras": "promovéis",
	"promover_ellos/ellas/ustedes": "promueven",

	"proponer_yo": "propongo",
	"proponer_tú": "propones",
	"proponer_él/ella/usted": "propone",
	"proponer_nosotros/nosotras": "proponemos",
	"proponer_vosotros/vosotras": "proponéis",
	"proponer_ellos/ellas/ustedes": "proponen",

	"proponerse_yo": "me propongo",
	"proponerse_tú": "te propones",
	"proponerse_él/ella/usted": "se propone",
	"proponerse_nosotros/nosotras": "nos proponemos",
	"proponerse_vosotros/vosotras": "os proponéis",
	"proponerse_ellos/ellas/ustedes": "se proponen",

	"proseguir_yo": "prosigo",
	"proseguir_tú": "prosigues",
	"proseguir_él/ella/usted": "prosigue",
	"proseguir_nosotros/nosotras": "proseguimos",
	"proseguir_vosotros/vosotras": "proseguís",
	"proseguir_ellos/ellas/ustedes": "prosiguen",

	"provenir_yo": "provengo",
	"provenir_tú": "provienes",
	"provenir_él/ella/usted": "proviene",
	"provenir_nosotros/nosotras": "provenimos",
	"provenir_vosotros/vosotras": "provenís",
	"provenir_ellos/ellas/ustedes": "provienen",

	"quebrar_yo": "quiebro",
	"quebrar_tú": "quiebras",
	"quebrar_él/ella/usted": "quiebra",
	"quebrar_nosotros/nosotras": "quebramos",
	"quebrar_vosotros/vosotras": "quebráis",
	"quebrar_ellos/ellas/ustedes": "quiebran",

	"quebrarse_yo": "me quiebro",
	"quebrarse_tú": "te quiebras",
	"quebrarse_él/ella/usted": "se quiebra",
	"quebrarse_nosotros/nosotras": "nos quebramos",
	"quebrarse_vosotros/vosotras": "os quebráis",
	"quebrarse_ellos/ellas/ustedes": "se quiebran",

	"querer_yo": "quiero",
	"querer_tú": "quieres",
	"querer_él/ella/usted": "quiere",
	"querer_nosotros/nosotras": "queremos",
	"querer_vosotros/vosotras": "queréis",
	"querer_ellos/ellas/ustedes": "quieren",

	"raer_yo": "raigo",
	"raer_tú": "raes",
	"raer_él/ella/usted": "rae",
	"raer_nosotros/nosotras": "raemos",
	"raer_vosotros/vosotras": "raéis",
	"raer_ellos/ellas/ustedes": "raen",

	"reaparecer_yo": "reaparezco",
	"reaparecer_tú": "reapareces",
	"reaparecer_él/ella/usted": "reaparece",
	"reaparecer_nosotros/nosotras": "reaparecemos",
	"reaparecer_vosotros/vosotras": "reaparecéis",
	"reaparecer_ellos/ellas/ustedes": "reaparecen",

	"recaer_yo": "recaigo",
	"recaer_tú": "recaes",
	"recaer_él/ella/usted": "recae",
	"recaer_nosotros/nosotras": "recaemos",
	"recaer_vosotros/vosotras": "recaéis",
	"recaer_ellos/ellas/ustedes": "recaen",

	"recomendar_yo": "recomiendo",
	"recomendar_tú": "recomiendas",
	"recomendar_él/ella/usted": "recomienda",
	"recomendar_nosotros/nosotras": "recomendamos",
	"recomendar_vosotros/vosotras": "recomendáis",
	"recomendar_ellos/ellas/ustedes": "recomiendan",

	"recomenzar_yo": "recomienzo",
	"recomenzar_tú": "recomienzas",
	"recomenzar_él/ella/usted": "recomienza",
	"recomenzar_nosotros/nosotras": "recomenzamos",
	"recomenzar_vosotros/vosotras": "recomenzáis",
	"recomenzar_ellos/ellas/ustedes": "recomienzan",

	"reconocer_yo": "reconozco",
	"reconocer_tú": "reconoces",
	"reconocer_él/ella/usted": "reconoce",
	"reconocer_nosotros/nosotras": "reconocemos",
	"reconocer_vosotros/vosotras": "reconocéis",
	"reconocer_ellos/ellas/ustedes": "reconocen",

	"recordar_yo": "recuerdo",
	"recordar_tú": "recuerdas",
	"recordar_él/ella/usted": "recuerda",
	"recordar_nosotros/nosotras": "recordamos",
	"recordar_vosotros/vosotras": "recordáis",
	"recordar_ellos/ellas/ustedes": "recuerdan",

	"reducir_yo": "reduzco",
	"reducir_tú": "reduces",
	"reducir_él/ella/usted": "reduce",
	"reducir_nosotros/nosotras": "reducimos",
	"reducir_vosotros/vosotras": "reducís",
	"reducir_ellos/ellas/ustedes": "reducen",

	"referir_yo": "refiero",
	"referir_tú": "refieres",
	"referir_él/ella/usted": "refiere",
	"referir_nosotros/nosotras": "referimos",
	"referir_vosotros/vosotras": "referís",
	"referir_ellos/ellas/ustedes": "refieren",

	"referirse_yo": "me refiero",
	"referirse_tú": "te refieres",
	"referirse_él/ella/usted": "se refiere",
	"referirse_nosotros/nosotras": "nos referimos",
	"referirse_vosotros/vosotras": "os referís",
	"referirse_ellos/ellas/ustedes": "se refieren",

	"reforzar_yo": "refuerzo",
	"reforzar_tú": "refuerzas",
	"reforzar_él/ella/usted": "refuerza",
	"reforzar_nosotros/nosotras": "reforzamos",
	"reforzar_vosotros/vosotras": "reforzáis",
	"reforzar_ellos/ellas/ustedes": "refuerzan",

	"regar_yo": "riego",
	"regar_tú": "riegas",
	"regar_él/ella/usted": "riega",
	"regar_nosotros/nosotras": "regamos",
	"regar_vosotros/vosotras": "regáis",
	"regar_ellos/ellas/ustedes": "riegan",

	"regir_yo": "rijo",
	"regir_tú": "riges",
	"regir_él/ella/usted": "rige",
	"regir_nosotros/nosotras": "regimos",
	"regir_vosotros/vosotras": "regís",
	"regir_ellos/ellas/ustedes": "rigen",

	"rehacer_yo": "rehago",
	"rehacer_tú": "rehaces",
	"rehacer_él/ella/usted": "rehace",
	"rehacer_nosotros/nosotras": "rehacemos",
	"rehacer_vosotros/vosotras": "rehacéis",
	"rehacer_ellos/ellas/ustedes": "rehacen",

	"reír_yo": "río",
	"reír_tú": "ríes",
	"reír_él/ella/usted": "ríe",
	"reír_nosotros/nosotras": "reímos",
	"reír_vosotros/vosotras": "reís",
	"reír_ellos/ellas/ustedes": "ríen",

	"reírse_yo": "me río",
	"reírse_tú": "te ríes",
	"reírse_él/ella/usted": "se ríe",
	"reírse_nosotros/nosotras": "nos reímos",
	"reírse_vosotros/vosotras": "os reís",
	"reírse_ellos/ellas/ustedes": "se ríen",

	"relucir_yo": "reluzco",
	"relucir_tú": "reluces",
	"relucir_él/ella/usted": "reluce",
	"relucir_nosotros/nosotras": "relucimos",
	"relucir_vosotros/vosotras": "relucís",
	"relucir_ellos/ellas/ustedes": "relucen",

	"remendar_yo": "remiendo",
	"remendar_tú": "remiendas",
	"remendar_él/ella/usted": "remienda",
	"remendar_nosotros/nosotras": "remendamos",
	"remendar_vosotros/vosotras": "remendáis",
	"remendar_ellos/ellas/ustedes": "remiendan",

	"remover_yo": "remuevo",
	"remover_tú": "remueves",
	"remover_él/ella/usted": "remueve",
	"remover_nosotros/nosotras": "removemos",
	"remover_vosotros/vosotras": "removéis",
	"remover_ellos/ellas/ustedes": "remueven",

	"renacer_yo": "renazco",
	"renacer_tú": "renaces",
	"renacer_él/ella/usted": "renace",
	"renacer_nosotros/nosotras": "renacemos",
	"renacer_vosotros/vosotras": "renacéis",
	"renacer_ellos/ellas/ustedes": "renacen",

	"rendir_yo": "rindo",
	"rendir_tú": "rindes",
	"rendir_él/ella/usted": "rinde",
	"rendir_nosotros/nosotras": "rendimos",
	"rendir_vosotros/vosotras": "rendís",
	"rendir_ellos/ellas/ustedes": "rinden",

	"rendirse_yo": "me rindo",
	"rendirse_tú": "te rindes",
	"rendirse_él/ella/usted": "se rinde",
	"rendirse_nosotros/nosotras": "nos rendimos",
	"rendirse_vosotros/vosotras": "os rendís",
	"rendirse_ellos/ellas/ustedes": "se rinden",

	"reñir_yo": "riño",
	"reñir_tú": "riñes",
	"reñir_él/ella/usted": "riñe",
	"reñir_nosotros/nosotras": "reñimos",
	"reñir_vosotros/vosotras": "reñís",
	"reñir_ellos/ellas/ustedes": "riñen",

	"repetir_yo": "repito",
	"repetir_tú": "repites",
	"repetir_él/ella/usted": "repite",
	"repetir_nosotros/nosotras": "repetimos",
	"repetir_vosotros/vosotras": "repetís",
	"repetir_ellos/ellas/ustedes": "repiten",

	"reponer_yo": "repongo",
	"reponer_tú": "repones",
	"reponer_él/ella/usted": "repone",
	"reponer_nosotros/nosotras": "reponemos",
	"reponer_vosotros/vosotras": "reponéis",
	"reponer_ellos/ellas/ustedes": "reponen",

	"reproducir_yo": "reproduzco",
	"reproducir_tú": "reproduces",
	"reproducir_él/ella/usted": "reproduce",
	"reproducir_nosotros/nosotras": "reproducimos",
	"reproducir_vosotros/vosotras": "reproducís",
	"reproducir_ellos/ellas/ustedes": "reproducen",

	"requerir_yo": "requiero",
	"requerir_tú": "requieres",
	"requerir_él/ella/usted": "requiere",
	"requerir_nosotros/nosotras": "requerimos",
	"requerir_vosotros/vosotras": "requerís",
	"requerir_ellos/ellas/ustedes": "requieren",

	"resolver_yo": "resuelvo",
	"resolver_tú": "resuelves",
	"resolver_él/ella/usted": "resuelve",
	"resolver_nosotros/nosotras": "resolvemos",
	"resolver_vosotros/vosotras": "resolvéis",
	"resolver_ellos/ellas/ustedes": "resuelven",

	"restablecer_yo": "restablezco",
	"restablecer_tú": "restableces",
	"restablecer_él/ella/usted": "restablece",
	"restablecer_nosotros/nosotras": "restablecemos",
	"restablecer_vosotros/vosotras": "restablecéis",
	"restablecer_ellos/ellas/ustedes": "restablecen",

	"retener_yo": "retengo",
	"retener_tú": "retienes",
	"retener_él/ella/usted": "retiene",
	"retener_nosotros/nosotras": "retenemos",
	"retener_vosotros/vosotras": "retenéis",
	"retener_ellos/ellas/ustedes": "retienen",

	"retorcer_yo": "retuerzo",
	"retorcer_tú": "retuerces",
	"retorcer_él/ella/usted": "retuerce",
	"retorcer_nosotros/nosotras": "retorcemos",
	"retorcer_vosotros/vosotras": "retorcéis",
	"retorcer_ellos/ellas/ustedes": "retuercen",

	"reventar_yo": "reviento",
	"reventar_tú": "revientas",
	"reventar_él/ella/usted": "revienta",
	"reventar_nosotros/nosotras": "reventamos",
	"reventar_vosotros/vosotras": "reventáis",
	"reventar_ellos/ellas/ustedes": "revientan",

	"revolver_yo": "revuelvo",
	"revolver_tú": "revuelves",
	"revolver_él/ella/usted": "revuelve",
	"revolver_nosotros/nosotras": "revolvemos",
	"revolver_vosotros/vosotras": "revolvéis",
	"revolver_ellos/ellas/ustedes": "revuelven",

	"rodar_yo": "ruedo",
	"rodar_tú": "ruedas",
	"rodar_él/ella/usted": "rueda",
	"rodar_nosotros/nosotras": "rodamos",
	"rodar_vosotros/vosotras": "rodáis",
	"rodar_ellos/ellas/ustedes": "ruedan",

	"roer_yo": "roo",
	"roer_tú": "roes",
	"roer_él/ella/usted": "roe",
	"roer_nosotros/nosotras": "roemos",
	"roer_vosotros/vosotras": "roéis",
	"roer_ellos/ellas/ustedes": "roen",

	"rogar_yo": "ruego",
	"rogar_tú": "ruegas",
	"rogar_él/ella/usted": "ruega",
	"rogar_nosotros/nosotras": "rogamos",
	"rogar_vosotros/vosotras": "rogáis",
	"rogar_ellos/ellas/ustedes": "ruegan",
	
	"saber_yo": "sé",
	"saber_tú": "sabes",
	"saber_él/ella/usted": "sabe",
	"saber_nosotros/nosotras": "sabemos",
	"saber_vosotros/vosotras": "sabéis",
	"saber_ellos/ellas/ustedes": "saben",

	"salir_yo": "salgo",
	"salir_tú": "sales",
	"salir_él/ella/usted": "sale",
	"salir_nosotros/nosotras": "salimos",
	"salir_vosotros/vosotras": "salís",
	"salir_ellos/ellas/ustedes": "salen",

	"salirse_yo": "me salgo",
	"salirse_tú": "te sales",
	"salirse_él/ella/usted": "se sale",
	"salirse_nosotros/nosotras": "nos salimos",
	"salirse_vosotros/vosotras": "os salís",
	"salirse_ellos/ellas/ustedes": "se salen",

	"satisfacer_yo": "satisfago",
	"satisfacer_tú": "satisfaces",
	"satisfacer_él/ella/usted": "satisface",
	"satisfacer_nosotros/nosotras": "satisfacemos",
	"satisfacer_vosotros/vosotras": "satisfacéis",
	"satisfacer_ellos/ellas/ustedes": "satisfacen",

	"seducir_yo": "seduzco",
	"seducir_tú": "seduces",
	"seducir_él/ella/usted": "seduce",
	"seducir_nosotros/nosotras": "seducimos",
	"seducir_vosotros/vosotras": "seducís",
	"seducir_ellos/ellas/ustedes": "seducen",

	"seguir_yo": "sigo",
	"seguir_tú": "sigues",
	"seguir_él/ella/usted": "sigue",
	"seguir_nosotros/nosotras": "seguimos",
	"seguir_vosotros/vosotras": "seguís",
	"seguir_ellos/ellas/ustedes": "siguen",

	"sembrar_yo": "siembro",
	"sembrar_tú": "siembras",
	"sembrar_él/ella/usted": "siembra",
	"sembrar_nosotros/nosotras": "sembramos",
	"sembrar_vosotros/vosotras": "sembráis",
	"sembrar_ellos/ellas/ustedes": "siembran",

	"sentar_yo": "siento",
	"sentar_tú": "sientas",
	"sentar_él/ella/usted": "sienta",
	"sentar_nosotros/nosotras": "sentamos",
	"sentar_vosotros/vosotras": "sentáis",
	"sentar_ellos/ellas/ustedes": "sientan",

	"sentarse_yo": "me siento",
	"sentarse_tú": "te sientas",
	"sentarse_él/ella/usted": "se sienta",
	"sentarse_nosotros/nosotras": "nos sentamos",
	"sentarse_vosotros/vosotras": "os sentáis",
	"sentarse_ellos/ellas/ustedes": "se sientan",

	"sentir_yo": "siento",
	"sentir_tú": "sientes",
	"sentir_él/ella/usted": "siente",
	"sentir_nosotros/nosotras": "sentimos",
	"sentir_vosotros/vosotras": "sentís",
	"sentir_ellos/ellas/ustedes": "sienten",

	"sentirse_yo": "me siento",
	"sentirse_tú": "te sientes",
	"sentirse_él/ella/usted": "se siente",
	"sentirse_nosotros/nosotras": "nos sentimos",
	"sentirse_vosotros/vosotras": "os sentís",
	"sentirse_ellos/ellas/ustedes": "se sienten",

	"ser_yo": "soy",
	"ser_tú": "eres",
	"ser_él/ella/usted": "es",
	"ser_nosotros/nosotras": "somos",
	"ser_vosotros/vosotras": "sois",
	"ser_ellos/ellas/ustedes": "son",

	"serrar_yo": "sierro",
	"serrar_tú": "sierras",
	"serrar_él/ella/usted": "sierra",
	"serrar_nosotros/nosotras": "serramos",
	"serrar_vosotros/vosotras": "serráis",
	"serrar_ellos/ellas/ustedes": "sierran",

	"servir_yo": "sirvo",
	"servir_tú": "sirves",
	"servir_él/ella/usted": "sirve",
	"servir_nosotros/nosotras": "servimos",
	"servir_vosotros/vosotras": "servís",
	"servir_ellos/ellas/ustedes": "sirven",

	"sobresalir_yo": "sobresalgo",
	"sobresalir_tú": "sobresales",
	"sobresalir_él/ella/usted": "sobresale",
	"sobresalir_nosotros/nosotras": "sobresalimos",
	"sobresalir_vosotros/vosotras": "sobresalís",
	"sobresalir_ellos/ellas/ustedes": "sobresalen",

	"sobrevolar_yo": "sobrevuelo",
	"sobrevolar_tú": "sobrevuelas",
	"sobrevolar_él/ella/usted": "sobrevuela",
	"sobrevolar_nosotros/nosotras": "sobrevolamos",
	"sobrevolar_vosotros/vosotras": "sobrevoláis",
	"sobrevolar_ellos/ellas/ustedes": "sobrevuelan",

	"sofreír_yo": "sofrío",
	"sofreír_tú": "sofríes",
	"sofreír_él/ella/usted": "sofríe",
	"sofreír_nosotros/nosotras": "sofreímos",
	"sofreír_vosotros/vosotras": "sofreís",
	"sofreír_ellos/ellas/ustedes": "sofríen",

	"soldar_yo": "sueldo",
	"soldar_tú": "sueldas",
	"soldar_él/ella/usted": "suelda",
	"soldar_nosotros/nosotras": "soldamos",
	"soldar_vosotros/vosotras": "soldáis",
	"soldar_ellos/ellas/ustedes": "sueldan",

	"soler_yo": "suelo",
	"soler_tú": "sueles",
	"soler_él/ella/usted": "suele",
	"soler_nosotros/nosotras": "solemos",
	"soler_vosotros/vosotras": "soléis",
	"soler_ellos/ellas/ustedes": "suelen",

	"soltar_yo": "suelto",
	"soltar_tú": "sueltas",
	"soltar_él/ella/usted": "suelta",
	"soltar_nosotros/nosotras": "soltamos",
	"soltar_vosotros/vosotras": "soltáis",
	"soltar_ellos/ellas/ustedes": "sueltan",

	"sonar_yo": "sueno",
	"sonar_tú": "suenas",
	"sonar_él/ella/usted": "suena",
	"sonar_nosotros/nosotras": "sonamos",
	"sonar_vosotros/vosotras": "sonáis",
	"sonar_ellos/ellas/ustedes": "suenan",

	"sonarse_yo": "me sueno",
	"sonarse_tú": "te suenas",
	"sonarse_él/ella/usted": "se suena",
	"sonarse_nosotros/nosotras": "nos sonamos",
	"sonarse_vosotros/vosotras": "os sonáis",
	"sonarse_ellos/ellas/ustedes": "se suenan",
	
	"sonreír_yo": "sonrío",
	"sonreír_tú": "sonríes",
	"sonreír_él/ella/usted": "sonríe",
	"sonreír_nosotros/nosotras": "sonreímos",
	"sonreír_vosotros/vosotras": "sonreís",
	"sonreír_ellos/ellas/ustedes": "sonríen",

	"soñar_yo": "sueño",
	"soñar_tú": "sueñas",
	"soñar_él/ella/usted": "sueña",
	"soñar_nosotros/nosotras": "soñamos",
	"soñar_vosotros/vosotras": "soñáis",
	"soñar_ellos/ellas/ustedes": "sueñan",

	"sosegar_yo": "sosiego",
	"sosegar_tú": "sosiegas",
	"sosegar_él/ella/usted": "sosiega",
	"sosegar_nosotros/nosotras": "sosegamos",
	"sosegar_vosotros/vosotras": "sosegáis",
	"sosegar_ellos/ellas/ustedes": "sosiegan",

	"sostener_yo": "sostengo",
	"sostener_tú": "sostienes",
	"sostener_él/ella/usted": "sostiene",
	"sostener_nosotros/nosotras": "sostenemos",
	"sostener_vosotros/vosotras": "sostenéis",
	"sostener_ellos/ellas/ustedes": "sostienen",

	"sugerir_yo": "sugiero",
	"sugerir_tú": "sugieres",
	"sugerir_él/ella/usted": "sugiere",
	"sugerir_nosotros/nosotras": "sugerimos",
	"sugerir_vosotros/vosotras": "sugerís",
	"sugerir_ellos/ellas/ustedes": "sugieren",

	"suponer_yo": "supongo",
	"suponer_tú": "supones",
	"suponer_él/ella/usted": "supone",
	"suponer_nosotros/nosotras": "suponemos",
	"suponer_vosotros/vosotras": "suponéis",
	"suponer_ellos/ellas/ustedes": "suponen",

	"surgir_yo": "surjo",
	"surgir_tú": "surges",
	"surgir_él/ella/usted": "surge",
	"surgir_nosotros/nosotras": "surgimos",
	"surgir_vosotros/vosotras": "surgís",
	"surgir_ellos/ellas/ustedes": "surgen",

	"sustraer_yo": "sustraigo",
	"sustraer_tú": "sustraes",
	"sustraer_él/ella/usted": "sustrae",
	"sustraer_nosotros/nosotras": "sustraemos",
	"sustraer_vosotros/vosotras": "sustraéis",
	"sustraer_ellos/ellas/ustedes": "sustraen",

	"temblar_yo": "tiemblo",
	"temblar_tú": "tiemblas",
	"temblar_él/ella/usted": "tiembla",
	"temblar_nosotros/nosotras": "temblamos",
	"temblar_vosotros/vosotras": "tembláis",
	"temblar_ellos/ellas/ustedes": "tiemblan",

	"tender_yo": "tiendo",
	"tender_tú": "tiendes",
	"tender_él/ella/usted": "tiende",
	"tender_nosotros/nosotras": "tendemos",
	"tender_vosotros/vosotras": "tendéis",
	"tender_ellos/ellas/ustedes": "tienden",

	"tener_yo": "tengo",
	"tener_tú": "tienes",
	"tener_él/ella/usted": "tiene",
	"tener_nosotros/nosotras": "tenemos",
	"tener_vosotros/vosotras": "tenéis",
	"tener_ellos/ellas/ustedes": "tienen",

	"tentar_yo": "tiento",
	"tentar_tú": "tientas",
	"tentar_él/ella/usted": "tienta",
	"tentar_nosotros/nosotras": "tentamos",
	"tentar_vosotros/vosotras": "tentáis",
	"tentar_ellos/ellas/ustedes": "tientan",

	"teñir_yo": "tiño",
	"teñir_tú": "tiñes",
	"teñir_él/ella/usted": "tiñe",
	"teñir_nosotros/nosotras": "teñimos",
	"teñir_vosotros/vosotras": "teñís",
	"teñir_ellos/ellas/ustedes": "tiñen",

	"torcer_yo": "tuerzo",
	"torcer_tú": "tuerces",
	"torcer_él/ella/usted": "tuerce",
	"torcer_nosotros/nosotras": "torcemos",
	"torcer_vosotros/vosotras": "torcéis",
	"torcer_ellos/ellas/ustedes": "tuercen",

	"tostar_yo": "tuesto",
	"tostar_tú": "tuestas",
	"tostar_él/ella/usted": "tuesta",
	"tostar_nosotros/nosotras": "tostamos",
	"tostar_vosotros/vosotras": "tostáis",
	"tostar_ellos/ellas/ustedes": "tuestan",

	"tostarse_yo": "me tuesto",
	"tostarse_tú": "te tuestas",
	"tostarse_él/ella/usted": "se tuesta",
	"tostarse_nosotros/nosotras": "nos tostamos",
	"tostarse_vosotros/vosotras": "os tostáis",
	"tostarse_ellos/ellas/ustedes": "se tuestan",

	"traducir_yo": "traduzco",
	"traducir_tú": "traduces",
	"traducir_él/ella/usted": "traduce",
	"traducir_nosotros/nosotras": "traducimos",
	"traducir_vosotros/vosotras": "traducís",
	"traducir_ellos/ellas/ustedes": "traducen",

	"traer_yo": "traigo",
	"traer_tú": "traes",
	"traer_él/ella/usted": "trae",
	"traer_nosotros/nosotras": "traemos",
	"traer_vosotros/vosotras": "traéis",
	"traer_ellos/ellas/ustedes": "traen",

	"transferir_yo": "transfiero",
	"transferir_tú": "transfieres",
	"transferir_él/ella/usted": "transfiere",
	"transferir_nosotros/nosotras": "transferimos",
	"transferir_vosotros/vosotras": "transferís",
	"transferir_ellos/ellas/ustedes": "transfieren",

	"tropezar_yo": "tropiezo",
	"tropezar_tú": "tropiezas",
	"tropezar_él/ella/usted": "tropieza",
	"tropezar_nosotros/nosotras": "tropezamos",
	"tropezar_vosotros/vosotras": "tropezáis",
	"tropezar_ellos/ellas/ustedes": "tropiezan",

	"valer_yo": "valgo",
	"valer_tú": "vales",
	"valer_él/ella/usted": "vale",
	"valer_nosotros/nosotras": "valemos",
	"valer_vosotros/vosotras": "valéis",
	"valer_ellos/ellas/ustedes": "valen",

	"vencer_yo": "venzo",
	"vencer_tú": "vences",
	"vencer_él/ella/usted": "vence",
	"vencer_nosotros/nosotras": "vencemos",
	"vencer_vosotros/vosotras": "vencéis",
	"vencer_ellos/ellas/ustedes": "vencen",

	"venir_yo": "vengo",
	"venir_tú": "vienes",
	"venir_él/ella/usted": "viene",
	"venir_nosotros/nosotras": "venimos",
	"venir_vosotros/vosotras": "venís",
	"venir_ellos/ellas/ustedes": "vienen",

	"ver_yo": "veo",
	"ver_tú": "ves",
	"ver_él/ella/usted": "ve",
	"ver_nosotros/nosotras": "vemos",
	"ver_vosotros/vosotras": "veis",
	"ver_ellos/ellas/ustedes": "ven",

	"verter_yo": "vierto",
	"verter_tú": "viertes",
	"verter_él/ella/usted": "vierte",
	"verter_nosotros/nosotras": "vertemos",
	"verter_vosotros/vosotras": "vertéis",
	"verter_ellos/ellas/ustedes": "vierten",

	"vestir_yo": "visto",
	"vestir_tú": "vistes",
	"vestir_él/ella/usted": "viste",
	"vestir_nosotros/nosotras": "vestimos",
	"vestir_vosotros/vosotras": "vestís",
	"vestir_ellos/ellas/ustedes": "visten",

	"vestirse_yo": "me visto",
	"vestirse_tú": "te vistes",
	"vestirse_él/ella/usted": "se viste",
	"vestirse_nosotros/nosotras": "nos vestimos",
	"vestirse_vosotros/vosotras": "os vestís",
	"vestirse_ellos/ellas/ustedes": "se visten",

	"volar_yo": "vuelo",
	"volar_tú": "vuelas",
	"volar_él/ella/usted": "vuela",
	"volar_nosotros/nosotras": "volamos",
	"volar_vosotros/vosotras": "voláis",
	"volar_ellos/ellas/ustedes": "vuelan",

	"volver_yo": "vuelvo",
	"volver_tú": "vuelves",
	"volver_él/ella/usted": "vuelve",
	"volver_nosotros/nosotras": "volvemos",
	"volver_vosotros/vosotras": "volvéis",
	"volver_ellos/ellas/ustedes": "vuelven",

	"volverse_yo": "me vuelvo",
	"volverse_tú": "te vuelves",
	"volverse_él/ella/usted": "se vuelve",
	"volverse_nosotros/nosotras": "nos volvemos",
	"volverse_vosotros/vosotras": "os volvéis",
	"volverse_ellos/ellas/ustedes": "se vuelven",

	"yacer_yo": "yazgo",
	"yacer_tú": "yaces",
	"yacer_él/ella/usted": "yace",
	"yacer_nosotros/nosotras": "yacemos",
	"yacer_vosotros/vosotras": "yacéis",
	"yacer_ellos/ellas/ustedes": "yacen",

	"yuxtaponer_yo": "yuxtapongo",
	"yuxtaponer_tú": "yuxtapones",
	"yuxtaponer_él/ella/usted": "yuxtapone",
	"yuxtaponer_nosotros/nosotras": "yuxtaponemos",
	"yuxtaponer_vosotros/vosotras": "yuxtaponéis",
	"yuxtaponer_ellos/ellas/ustedes": "yuxtaponen",
}



